/* Service worker — cache hors ligne (1re visite en Wi‑Fi, puis utilisable sans réseau dans Safari).
   - Code, styles, données : réseau d’abord (mises à jour immédiates), cache si hors ligne / lent.
   - Librairie MapLibre et images : cache d’abord ; les images vivent dans IMG_CACHE, conservé entre
     les versions. Installation = vignettes seulement ; photos complètes en tâche de fond quand la page
     envoie PRECACHE_IMAGES (2 à la fois, seules les manquantes ou modifiées : empreinte IMG_HASH).
   - Tuiles de carte : cache séparé TILE_CACHE, géré par src/map/offline-tiles.js, jamais purgé ici.
   Version : scripts/bump-version.mjs · liste ASSETS : scripts/gen-precache.mjs. */
const CACHE = "japan-trip-2026-v181";
const TILE_CACHE = "japan-tiles-v1";
/** Photos : cache gardé d’une version à l’autre (seules les nouvelles sont téléchargées). */
const IMG_CACHE = "japan-img-v1";
const isImage = (url) => url.includes("/img/");
/** Photo complète (≈ 230 Ko) : préchargée en tâche de fond, pas à l’installation. Les vignettes (thumb/) si. */
const isFullPhoto = (url) => /\/img\/(activities|hotels)\/[^/]+$/.test(url);
const NETWORK_TIMEOUT_MS = 4000;

// <precache> — généré par scripts/gen-precache.mjs, ne pas éditer à la main
const ASSETS = [
  "./",
  "./index.html",
  "./manifest.webmanifest",
  "./sw.js",
  "./data/cities.json",
  "./data/days.json",
  "./data/journeys.json",
  "./data/legs.json",
  "./data/photos.json",
  "./data/phrases.json",
  "./data/places-meta.json",
  "./data/practical.json",
  "./data/prep.json",
  "./data/trip.json",
  "./img/activities/akihabara-2.jpg",
  "./img/activities/akihabara-3.jpg",
  "./img/activities/akihabara.jpg",
  "./img/activities/animate.jpg",
  "./img/activities/arashiyama-2.jpg",
  "./img/activities/arashiyama-3.jpg",
  "./img/activities/arashiyama.jpg",
  "./img/activities/character-street-2.jpg",
  "./img/activities/character-street-3.jpg",
  "./img/activities/character-street.jpg",
  "./img/activities/chureito-2.jpg",
  "./img/activities/chureito-3.jpg",
  "./img/activities/chureito.jpg",
  "./img/activities/daigo-2.jpg",
  "./img/activities/daigo-3.jpg",
  "./img/activities/daigo.jpg",
  "./img/activities/denden-2.jpg",
  "./img/activities/denden.jpg",
  "./img/activities/dotonbori-2.jpg",
  "./img/activities/dotonbori-3.jpg",
  "./img/activities/dotonbori.jpg",
  "./img/activities/fujiq-2.jpg",
  "./img/activities/fujiq-3.jpg",
  "./img/activities/fujiq.jpg",
  "./img/activities/fushimi-2.jpg",
  "./img/activities/fushimi-3.jpg",
  "./img/activities/fushimi.jpg",
  "./img/activities/ginza-2.jpg",
  "./img/activities/ginza-3.jpg",
  "./img/activities/ginza.jpg",
  "./img/activities/gold-leaf-2.jpg",
  "./img/activities/gold-leaf.jpg",
  "./img/activities/harajuku-2.jpg",
  "./img/activities/harajuku-3.jpg",
  "./img/activities/harajuku.jpg",
  "./img/activities/higashi-chaya-2.jpg",
  "./img/activities/higashi-chaya-3.jpg",
  "./img/activities/higashi-chaya.jpg",
  "./img/activities/hozenji-2.jpg",
  "./img/activities/hozenji-3.jpg",
  "./img/activities/hozenji.jpg",
  "./img/activities/imperial-2.jpg",
  "./img/activities/imperial-3.jpg",
  "./img/activities/imperial.jpg",
  "./img/activities/itchiku-2.jpg",
  "./img/activities/itchiku-3.jpg",
  "./img/activities/itchiku.jpg",
  "./img/activities/jinya-2.jpg",
  "./img/activities/jinya-3.jpg",
  "./img/activities/jinya.jpg",
  "./img/activities/kanazawa-castle-2.jpg",
  "./img/activities/kanazawa-castle-3.jpg",
  "./img/activities/kanazawa-castle.jpg",
  "./img/activities/kanazawa-museum-2.jpg",
  "./img/activities/kanazawa-museum-3.jpg",
  "./img/activities/kanazawa-museum.jpg",
  "./img/activities/kasuga-2.jpg",
  "./img/activities/kasuga-3.jpg",
  "./img/activities/kasuga.jpg",
  "./img/activities/kawaguchi-2.jpg",
  "./img/activities/kawaguchi-3.jpg",
  "./img/activities/kawaguchi.jpg",
  "./img/activities/kenrokuen-2.jpg",
  "./img/activities/kenrokuen-3.jpg",
  "./img/activities/kenrokuen.jpg",
  "./img/activities/kinkakuji-2.jpg",
  "./img/activities/kinkakuji-3.jpg",
  "./img/activities/kinkakuji.jpg",
  "./img/activities/kiyomizu-2.jpg",
  "./img/activities/kiyomizu-3.jpg",
  "./img/activities/kiyomizu.jpg",
  "./img/activities/kofukuji-2.jpg",
  "./img/activities/kofukuji-3.jpg",
  "./img/activities/kofukuji.jpg",
  "./img/activities/kuromon-2.jpg",
  "./img/activities/kuromon-3.jpg",
  "./img/activities/kuromon.jpg",
  "./img/activities/meiji-2.jpg",
  "./img/activities/meiji-3.jpg",
  "./img/activities/meiji.jpg",
  "./img/activities/miyagawa-2.jpg",
  "./img/activities/miyagawa-3.jpg",
  "./img/activities/miyagawa.jpg",
  "./img/activities/momiji.jpg",
  "./img/activities/music-forest-2.jpg",
  "./img/activities/music-forest-3.jpg",
  "./img/activities/music-forest.jpg",
  "./img/activities/myoryuji.jpg",
  "./img/activities/nagamachi-2.jpg",
  "./img/activities/nagamachi-3.jpg",
  "./img/activities/nagamachi.jpg",
  "./img/activities/namba-yasaka-2.jpg",
  "./img/activities/namba-yasaka-3.jpg",
  "./img/activities/namba-yasaka.jpg",
  "./img/activities/nara-park-2.jpg",
  "./img/activities/nara-park-3.jpg",
  "./img/activities/nara-park.jpg",
  "./img/activities/nijo-2.jpg",
  "./img/activities/nijo-3.jpg",
  "./img/activities/nijo.jpg",
  "./img/activities/nishi-chaya-2.jpg",
  "./img/activities/nishi-chaya-3.jpg",
  "./img/activities/nishi-chaya.jpg",
  "./img/activities/nishiki-2.jpg",
  "./img/activities/nishiki-3.jpg",
  "./img/activities/nishiki.jpg",
  "./img/activities/odaiba-2.jpg",
  "./img/activities/odaiba-3.jpg",
  "./img/activities/odaiba.jpg",
  "./img/activities/omicho-2.jpg",
  "./img/activities/omicho-3.jpg",
  "./img/activities/omicho.jpg",
  "./img/activities/osaka-castle-2.jpg",
  "./img/activities/osaka-castle-3.jpg",
  "./img/activities/osaka-castle.jpg",
  "./img/activities/oshino-2.jpg",
  "./img/activities/oshino-3.jpg",
  "./img/activities/oshino.jpg",
  "./img/activities/oyama-2.jpg",
  "./img/activities/oyama-3.jpg",
  "./img/activities/oyama.jpg",
  "./img/activities/philosopher-2.jpg",
  "./img/activities/philosopher-3.jpg",
  "./img/activities/philosopher.jpg",
  "./img/activities/pontocho-2.jpg",
  "./img/activities/pontocho-3.jpg",
  "./img/activities/pontocho.jpg",
  "./img/activities/ropeway-2.jpg",
  "./img/activities/ropeway-3.jpg",
  "./img/activities/ropeway.jpg",
  "./img/activities/saiko-2.jpg",
  "./img/activities/saiko-3.jpg",
  "./img/activities/saiko.jpg",
  "./img/activities/sanmachi-2.jpg",
  "./img/activities/sanmachi.jpg",
  "./img/activities/sensoji-2.jpg",
  "./img/activities/sensoji-3.jpg",
  "./img/activities/sensoji.jpg",
  "./img/activities/shibuya-2.jpg",
  "./img/activities/shibuya-3.jpg",
  "./img/activities/shibuya.jpg",
  "./img/activities/shinjuku-2.jpg",
  "./img/activities/shinjuku-3.jpg",
  "./img/activities/shinjuku.jpg",
  "./img/activities/shinsaibashi-2.jpg",
  "./img/activities/shinsaibashi-3.jpg",
  "./img/activities/shinsaibashi.jpg",
  "./img/activities/shinsekai-2.jpg",
  "./img/activities/shinsekai.jpg",
  "./img/activities/shirakawa-2.jpg",
  "./img/activities/shirakawa-3.jpg",
  "./img/activities/shirakawa.jpg",
  "./img/activities/sumida-2.jpg",
  "./img/activities/sumida-3.jpg",
  "./img/activities/sumida.jpg",
  "./img/activities/tea-2.jpg",
  "./img/activities/tea-3.jpg",
  "./img/activities/tea.jpg",
  "./img/activities/teamlab-2.jpg",
  "./img/activities/teamlab-3.jpg",
  "./img/activities/teamlab.jpg",
  "./img/activities/teramachi.jpg",
  "./img/activities/thumb/akihabara-2.jpg",
  "./img/activities/thumb/akihabara-3.jpg",
  "./img/activities/thumb/akihabara.jpg",
  "./img/activities/thumb/animate.jpg",
  "./img/activities/thumb/arashiyama-2.jpg",
  "./img/activities/thumb/arashiyama-3.jpg",
  "./img/activities/thumb/arashiyama.jpg",
  "./img/activities/thumb/character-street-2.jpg",
  "./img/activities/thumb/character-street-3.jpg",
  "./img/activities/thumb/character-street.jpg",
  "./img/activities/thumb/chureito-2.jpg",
  "./img/activities/thumb/chureito-3.jpg",
  "./img/activities/thumb/chureito.jpg",
  "./img/activities/thumb/daigo-2.jpg",
  "./img/activities/thumb/daigo-3.jpg",
  "./img/activities/thumb/daigo.jpg",
  "./img/activities/thumb/denden-2.jpg",
  "./img/activities/thumb/denden.jpg",
  "./img/activities/thumb/dotonbori-2.jpg",
  "./img/activities/thumb/dotonbori-3.jpg",
  "./img/activities/thumb/dotonbori.jpg",
  "./img/activities/thumb/fujiq-2.jpg",
  "./img/activities/thumb/fujiq-3.jpg",
  "./img/activities/thumb/fujiq.jpg",
  "./img/activities/thumb/fushimi-2.jpg",
  "./img/activities/thumb/fushimi-3.jpg",
  "./img/activities/thumb/fushimi.jpg",
  "./img/activities/thumb/ginza-2.jpg",
  "./img/activities/thumb/ginza-3.jpg",
  "./img/activities/thumb/ginza.jpg",
  "./img/activities/thumb/gold-leaf-2.jpg",
  "./img/activities/thumb/gold-leaf.jpg",
  "./img/activities/thumb/harajuku-2.jpg",
  "./img/activities/thumb/harajuku-3.jpg",
  "./img/activities/thumb/harajuku.jpg",
  "./img/activities/thumb/higashi-chaya-2.jpg",
  "./img/activities/thumb/higashi-chaya-3.jpg",
  "./img/activities/thumb/higashi-chaya.jpg",
  "./img/activities/thumb/hozenji-2.jpg",
  "./img/activities/thumb/hozenji-3.jpg",
  "./img/activities/thumb/hozenji.jpg",
  "./img/activities/thumb/imperial-2.jpg",
  "./img/activities/thumb/imperial-3.jpg",
  "./img/activities/thumb/imperial.jpg",
  "./img/activities/thumb/itchiku-2.jpg",
  "./img/activities/thumb/itchiku-3.jpg",
  "./img/activities/thumb/itchiku.jpg",
  "./img/activities/thumb/jinya-2.jpg",
  "./img/activities/thumb/jinya-3.jpg",
  "./img/activities/thumb/jinya.jpg",
  "./img/activities/thumb/kanazawa-castle-2.jpg",
  "./img/activities/thumb/kanazawa-castle-3.jpg",
  "./img/activities/thumb/kanazawa-castle.jpg",
  "./img/activities/thumb/kanazawa-museum-2.jpg",
  "./img/activities/thumb/kanazawa-museum-3.jpg",
  "./img/activities/thumb/kanazawa-museum.jpg",
  "./img/activities/thumb/kasuga-2.jpg",
  "./img/activities/thumb/kasuga-3.jpg",
  "./img/activities/thumb/kasuga.jpg",
  "./img/activities/thumb/kawaguchi-2.jpg",
  "./img/activities/thumb/kawaguchi-3.jpg",
  "./img/activities/thumb/kawaguchi.jpg",
  "./img/activities/thumb/kenrokuen-2.jpg",
  "./img/activities/thumb/kenrokuen-3.jpg",
  "./img/activities/thumb/kenrokuen.jpg",
  "./img/activities/thumb/kinkakuji-2.jpg",
  "./img/activities/thumb/kinkakuji-3.jpg",
  "./img/activities/thumb/kinkakuji.jpg",
  "./img/activities/thumb/kiyomizu-2.jpg",
  "./img/activities/thumb/kiyomizu-3.jpg",
  "./img/activities/thumb/kiyomizu.jpg",
  "./img/activities/thumb/kofukuji-2.jpg",
  "./img/activities/thumb/kofukuji-3.jpg",
  "./img/activities/thumb/kofukuji.jpg",
  "./img/activities/thumb/kuromon-2.jpg",
  "./img/activities/thumb/kuromon-3.jpg",
  "./img/activities/thumb/kuromon.jpg",
  "./img/activities/thumb/meiji-2.jpg",
  "./img/activities/thumb/meiji-3.jpg",
  "./img/activities/thumb/meiji.jpg",
  "./img/activities/thumb/miyagawa-2.jpg",
  "./img/activities/thumb/miyagawa-3.jpg",
  "./img/activities/thumb/miyagawa.jpg",
  "./img/activities/thumb/momiji.jpg",
  "./img/activities/thumb/music-forest-2.jpg",
  "./img/activities/thumb/music-forest-3.jpg",
  "./img/activities/thumb/music-forest.jpg",
  "./img/activities/thumb/myoryuji.jpg",
  "./img/activities/thumb/nagamachi-2.jpg",
  "./img/activities/thumb/nagamachi-3.jpg",
  "./img/activities/thumb/nagamachi.jpg",
  "./img/activities/thumb/namba-yasaka-2.jpg",
  "./img/activities/thumb/namba-yasaka-3.jpg",
  "./img/activities/thumb/namba-yasaka.jpg",
  "./img/activities/thumb/nara-park-2.jpg",
  "./img/activities/thumb/nara-park-3.jpg",
  "./img/activities/thumb/nara-park.jpg",
  "./img/activities/thumb/nijo-2.jpg",
  "./img/activities/thumb/nijo-3.jpg",
  "./img/activities/thumb/nijo.jpg",
  "./img/activities/thumb/nishi-chaya-2.jpg",
  "./img/activities/thumb/nishi-chaya-3.jpg",
  "./img/activities/thumb/nishi-chaya.jpg",
  "./img/activities/thumb/nishiki-2.jpg",
  "./img/activities/thumb/nishiki-3.jpg",
  "./img/activities/thumb/nishiki.jpg",
  "./img/activities/thumb/odaiba-2.jpg",
  "./img/activities/thumb/odaiba-3.jpg",
  "./img/activities/thumb/odaiba.jpg",
  "./img/activities/thumb/omicho-2.jpg",
  "./img/activities/thumb/omicho-3.jpg",
  "./img/activities/thumb/omicho.jpg",
  "./img/activities/thumb/osaka-castle-2.jpg",
  "./img/activities/thumb/osaka-castle-3.jpg",
  "./img/activities/thumb/osaka-castle.jpg",
  "./img/activities/thumb/oshino-2.jpg",
  "./img/activities/thumb/oshino-3.jpg",
  "./img/activities/thumb/oshino.jpg",
  "./img/activities/thumb/oyama-2.jpg",
  "./img/activities/thumb/oyama-3.jpg",
  "./img/activities/thumb/oyama.jpg",
  "./img/activities/thumb/philosopher-2.jpg",
  "./img/activities/thumb/philosopher-3.jpg",
  "./img/activities/thumb/philosopher.jpg",
  "./img/activities/thumb/pontocho-2.jpg",
  "./img/activities/thumb/pontocho-3.jpg",
  "./img/activities/thumb/pontocho.jpg",
  "./img/activities/thumb/ropeway-2.jpg",
  "./img/activities/thumb/ropeway-3.jpg",
  "./img/activities/thumb/ropeway.jpg",
  "./img/activities/thumb/saiko-2.jpg",
  "./img/activities/thumb/saiko-3.jpg",
  "./img/activities/thumb/saiko.jpg",
  "./img/activities/thumb/sanmachi-2.jpg",
  "./img/activities/thumb/sanmachi.jpg",
  "./img/activities/thumb/sensoji-2.jpg",
  "./img/activities/thumb/sensoji-3.jpg",
  "./img/activities/thumb/sensoji.jpg",
  "./img/activities/thumb/shibuya-2.jpg",
  "./img/activities/thumb/shibuya-3.jpg",
  "./img/activities/thumb/shibuya.jpg",
  "./img/activities/thumb/shinjuku-2.jpg",
  "./img/activities/thumb/shinjuku-3.jpg",
  "./img/activities/thumb/shinjuku.jpg",
  "./img/activities/thumb/shinsaibashi-2.jpg",
  "./img/activities/thumb/shinsaibashi-3.jpg",
  "./img/activities/thumb/shinsaibashi.jpg",
  "./img/activities/thumb/shinsekai-2.jpg",
  "./img/activities/thumb/shinsekai.jpg",
  "./img/activities/thumb/shirakawa-2.jpg",
  "./img/activities/thumb/shirakawa-3.jpg",
  "./img/activities/thumb/shirakawa.jpg",
  "./img/activities/thumb/sumida-2.jpg",
  "./img/activities/thumb/sumida-3.jpg",
  "./img/activities/thumb/sumida.jpg",
  "./img/activities/thumb/tea-2.jpg",
  "./img/activities/thumb/tea-3.jpg",
  "./img/activities/thumb/tea.jpg",
  "./img/activities/thumb/teamlab-2.jpg",
  "./img/activities/thumb/teamlab-3.jpg",
  "./img/activities/thumb/teamlab.jpg",
  "./img/activities/thumb/teramachi.jpg",
  "./img/activities/thumb/todaiji-2.jpg",
  "./img/activities/thumb/todaiji-3.jpg",
  "./img/activities/thumb/todaiji.jpg",
  "./img/activities/thumb/tokyo-tower-2.jpg",
  "./img/activities/thumb/tokyo-tower-3.jpg",
  "./img/activities/thumb/tokyo-tower.jpg",
  "./img/activities/thumb/ueno-2.jpg",
  "./img/activities/thumb/ueno-3.jpg",
  "./img/activities/thumb/ueno.jpg",
  "./img/activities/thumb/usj-2.jpg",
  "./img/activities/thumb/usj-3.jpg",
  "./img/activities/thumb/usj.jpg",
  "./img/activities/thumb/wagashi-2.jpg",
  "./img/activities/thumb/wagashi-3.jpg",
  "./img/activities/thumb/wagashi.jpg",
  "./img/activities/thumb/yanaka-2.jpg",
  "./img/activities/thumb/yanaka-3.jpg",
  "./img/activities/thumb/yanaka.jpg",
  "./img/activities/thumb/yasaka-2.jpg",
  "./img/activities/thumb/yasaka-3.jpg",
  "./img/activities/thumb/yasaka.jpg",
  "./img/activities/todaiji-2.jpg",
  "./img/activities/todaiji-3.jpg",
  "./img/activities/todaiji.jpg",
  "./img/activities/tokyo-tower-2.jpg",
  "./img/activities/tokyo-tower-3.jpg",
  "./img/activities/tokyo-tower.jpg",
  "./img/activities/ueno-2.jpg",
  "./img/activities/ueno-3.jpg",
  "./img/activities/ueno.jpg",
  "./img/activities/usj-2.jpg",
  "./img/activities/usj-3.jpg",
  "./img/activities/usj.jpg",
  "./img/activities/wagashi-2.jpg",
  "./img/activities/wagashi-3.jpg",
  "./img/activities/wagashi.jpg",
  "./img/activities/yanaka-2.jpg",
  "./img/activities/yanaka-3.jpg",
  "./img/activities/yanaka.jpg",
  "./img/activities/yasaka-2.jpg",
  "./img/activities/yasaka-3.jpg",
  "./img/activities/yasaka.jpg",
  "./img/hotels/agora-kyoto-2.jpg",
  "./img/hotels/agora-kyoto-3.jpg",
  "./img/hotels/agora-kyoto-4.jpg",
  "./img/hotels/agora-kyoto.jpg",
  "./img/hotels/deer-park-nara-2.jpg",
  "./img/hotels/deer-park-nara-3.jpg",
  "./img/hotels/deer-park-nara-4.jpg",
  "./img/hotels/deer-park-nara.jpg",
  "./img/hotels/garner-osaka-2.jpg",
  "./img/hotels/garner-osaka-3.jpg",
  "./img/hotels/garner-osaka-4.jpg",
  "./img/hotels/garner-osaka.jpg",
  "./img/hotels/henn-na-kanazawa-2.jpg",
  "./img/hotels/henn-na-kanazawa-3.jpg",
  "./img/hotels/henn-na-kanazawa-4.jpg",
  "./img/hotels/henn-na-kanazawa.jpg",
  "./img/hotels/homenest-akihabara-2.jpg",
  "./img/hotels/homenest-akihabara-3.jpg",
  "./img/hotels/homenest-akihabara-4.jpg",
  "./img/hotels/homenest-akihabara-5.jpg",
  "./img/hotels/homenest-akihabara-6.jpg",
  "./img/hotels/homenest-akihabara.jpg",
  "./img/hotels/kawaguchiko-2.jpg",
  "./img/hotels/kawaguchiko-3.jpg",
  "./img/hotels/kawaguchiko-4.jpg",
  "./img/hotels/kawaguchiko.jpg",
  "./img/hotels/mercure-takayama-2.jpg",
  "./img/hotels/mercure-takayama-3.jpg",
  "./img/hotels/mercure-takayama-4.jpg",
  "./img/hotels/mercure-takayama.jpg",
  "./img/hotels/royal-park-haneda-2.jpg",
  "./img/hotels/royal-park-haneda-3.jpg",
  "./img/hotels/royal-park-haneda-4.jpg",
  "./img/hotels/royal-park-haneda.jpg",
  "./img/hotels/thumb/agora-kyoto-2.jpg",
  "./img/hotels/thumb/agora-kyoto-3.jpg",
  "./img/hotels/thumb/agora-kyoto-4.jpg",
  "./img/hotels/thumb/agora-kyoto.jpg",
  "./img/hotels/thumb/deer-park-nara-2.jpg",
  "./img/hotels/thumb/deer-park-nara-3.jpg",
  "./img/hotels/thumb/deer-park-nara-4.jpg",
  "./img/hotels/thumb/deer-park-nara.jpg",
  "./img/hotels/thumb/garner-osaka-2.jpg",
  "./img/hotels/thumb/garner-osaka-3.jpg",
  "./img/hotels/thumb/garner-osaka-4.jpg",
  "./img/hotels/thumb/garner-osaka.jpg",
  "./img/hotels/thumb/henn-na-kanazawa-2.jpg",
  "./img/hotels/thumb/henn-na-kanazawa-3.jpg",
  "./img/hotels/thumb/henn-na-kanazawa-4.jpg",
  "./img/hotels/thumb/henn-na-kanazawa.jpg",
  "./img/hotels/thumb/homenest-akihabara-2.jpg",
  "./img/hotels/thumb/homenest-akihabara-3.jpg",
  "./img/hotels/thumb/homenest-akihabara-4.jpg",
  "./img/hotels/thumb/homenest-akihabara-5.jpg",
  "./img/hotels/thumb/homenest-akihabara-6.jpg",
  "./img/hotels/thumb/homenest-akihabara.jpg",
  "./img/hotels/thumb/kawaguchiko-2.jpg",
  "./img/hotels/thumb/kawaguchiko-3.jpg",
  "./img/hotels/thumb/kawaguchiko-4.jpg",
  "./img/hotels/thumb/kawaguchiko.jpg",
  "./img/hotels/thumb/mercure-takayama-2.jpg",
  "./img/hotels/thumb/mercure-takayama-3.jpg",
  "./img/hotels/thumb/mercure-takayama-4.jpg",
  "./img/hotels/thumb/mercure-takayama.jpg",
  "./img/hotels/thumb/royal-park-haneda-2.jpg",
  "./img/hotels/thumb/royal-park-haneda-3.jpg",
  "./img/hotels/thumb/royal-park-haneda-4.jpg",
  "./img/hotels/thumb/royal-park-haneda.jpg",
  "./img/icon-180.png",
  "./img/icon-192.png",
  "./img/icon-512.png",
  "./img/logo.svg",
  "./lib/maplibre/maplibre-gl.css",
  "./lib/maplibre/maplibre-gl.js",
  "./src/config.js",
  "./src/core/checklist-store.js",
  "./src/core/data.js",
  "./src/core/dates.js",
  "./src/core/dom.js",
  "./src/core/elements.js",
  "./src/core/env.js",
  "./src/core/hooks.js",
  "./src/core/state.js",
  "./src/domain/bookings.js",
  "./src/domain/classify.js",
  "./src/domain/itinerary.js",
  "./src/domain/legs.js",
  "./src/domain/photos.js",
  "./src/domain/places.js",
  "./src/domain/trip.js",
  "./src/main.js",
  "./src/map/city.js",
  "./src/map/controller.js",
  "./src/map/country.js",
  "./src/map/day-route.js",
  "./src/map/geo.js",
  "./src/map/map-style.js",
  "./src/map/map-view.js",
  "./src/map/offline-tiles.js",
  "./src/map/routes.js",
  "./src/pwa/sw-register.js",
  "./src/shared/icons.js",
  "./src/ui/alerts.js",
  "./src/ui/app-shell.js",
  "./src/ui/city-list.js",
  "./src/ui/map-controls.js",
  "./src/ui/panels/city-panel.js",
  "./src/ui/panels/leg-panel.js",
  "./src/ui/panels/panel.js",
  "./src/ui/panels/sheet.js",
  "./src/ui/phrase-show.js",
  "./src/ui/tabs.js",
  "./src/ui/templates.js",
  "./src/ui/theme.js",
  "./src/ui/views/fx-converter.js",
  "./src/ui/views/onsite-view.js",
  "./src/ui/views/prep-view.js",
  "./src/ui/views/print.js",
  "./src/ui/views/settings-view.js",
  "./src/ui/views/weather.js",
  "./styles/base.css",
  "./styles/components.css",
  "./styles/map.css",
  "./styles/mobile.css",
  "./styles/panel.css",
  "./styles/print.css",
  "./styles/settings.css",
  "./styles/standalone.css",
  "./styles/theme-light.css",
  "./styles/tokens.css",
  "./styles/views.css"
];
const IMG_HASH = {
  "./img/activities/akihabara-2.jpg": "ab1d0f133c",
  "./img/activities/akihabara-3.jpg": "b370dcde4e",
  "./img/activities/akihabara.jpg": "f637c0edc5",
  "./img/activities/animate.jpg": "1674f96955",
  "./img/activities/arashiyama-2.jpg": "d5f05bdfdf",
  "./img/activities/arashiyama-3.jpg": "0bffcba6f2",
  "./img/activities/arashiyama.jpg": "7723cec575",
  "./img/activities/character-street-2.jpg": "efd2d9ec8e",
  "./img/activities/character-street-3.jpg": "f5b42e4227",
  "./img/activities/character-street.jpg": "2f88fb9d75",
  "./img/activities/chureito-2.jpg": "f6f0f114d3",
  "./img/activities/chureito-3.jpg": "ad3974564a",
  "./img/activities/chureito.jpg": "e921442f5b",
  "./img/activities/daigo-2.jpg": "ed48aa109b",
  "./img/activities/daigo-3.jpg": "d23e998432",
  "./img/activities/daigo.jpg": "3a07da833f",
  "./img/activities/denden-2.jpg": "f2725ec705",
  "./img/activities/denden.jpg": "9f3be029b6",
  "./img/activities/dotonbori-2.jpg": "51bebfc1d5",
  "./img/activities/dotonbori-3.jpg": "dd6089f55b",
  "./img/activities/dotonbori.jpg": "382cf51e85",
  "./img/activities/fujiq-2.jpg": "b9746cf978",
  "./img/activities/fujiq-3.jpg": "ff19259fef",
  "./img/activities/fujiq.jpg": "5bd77c599b",
  "./img/activities/fushimi-2.jpg": "d064da4aa1",
  "./img/activities/fushimi-3.jpg": "c1e685ea14",
  "./img/activities/fushimi.jpg": "e7c744515f",
  "./img/activities/ginza-2.jpg": "d519c10faf",
  "./img/activities/ginza-3.jpg": "4ad4a9b522",
  "./img/activities/ginza.jpg": "528ec67800",
  "./img/activities/gold-leaf-2.jpg": "a93f3812d9",
  "./img/activities/gold-leaf.jpg": "415269b3e1",
  "./img/activities/harajuku-2.jpg": "d26ca31eb8",
  "./img/activities/harajuku-3.jpg": "6963745d36",
  "./img/activities/harajuku.jpg": "92be871a1d",
  "./img/activities/higashi-chaya-2.jpg": "e1afae233e",
  "./img/activities/higashi-chaya-3.jpg": "2af285f481",
  "./img/activities/higashi-chaya.jpg": "7764f93c72",
  "./img/activities/hozenji-2.jpg": "e3d7cb54c4",
  "./img/activities/hozenji-3.jpg": "f064ce1aae",
  "./img/activities/hozenji.jpg": "7325d24a9e",
  "./img/activities/imperial-2.jpg": "a6274a401a",
  "./img/activities/imperial-3.jpg": "a7cc53d8d7",
  "./img/activities/imperial.jpg": "85f2ba5185",
  "./img/activities/itchiku-2.jpg": "fe09a16b53",
  "./img/activities/itchiku-3.jpg": "874c9036fa",
  "./img/activities/itchiku.jpg": "31f9fbc502",
  "./img/activities/jinya-2.jpg": "e60f76a085",
  "./img/activities/jinya-3.jpg": "b34f012ded",
  "./img/activities/jinya.jpg": "bed4ca8561",
  "./img/activities/kanazawa-castle-2.jpg": "523d1c042b",
  "./img/activities/kanazawa-castle-3.jpg": "86c7ae8e9d",
  "./img/activities/kanazawa-castle.jpg": "16684554e7",
  "./img/activities/kanazawa-museum-2.jpg": "02c8bcbb20",
  "./img/activities/kanazawa-museum-3.jpg": "e95fa8e7c3",
  "./img/activities/kanazawa-museum.jpg": "6686f07e60",
  "./img/activities/kasuga-2.jpg": "22ef79ac40",
  "./img/activities/kasuga-3.jpg": "e0514fe9b8",
  "./img/activities/kasuga.jpg": "cefd7538cf",
  "./img/activities/kawaguchi-2.jpg": "538be19d0e",
  "./img/activities/kawaguchi-3.jpg": "069c0ce332",
  "./img/activities/kawaguchi.jpg": "26a01fa5e4",
  "./img/activities/kenrokuen-2.jpg": "34be4c25e6",
  "./img/activities/kenrokuen-3.jpg": "8f76f920cb",
  "./img/activities/kenrokuen.jpg": "6c540d37e4",
  "./img/activities/kinkakuji-2.jpg": "5afe5b4bef",
  "./img/activities/kinkakuji-3.jpg": "4234c16e45",
  "./img/activities/kinkakuji.jpg": "6ada192415",
  "./img/activities/kiyomizu-2.jpg": "f887728e1d",
  "./img/activities/kiyomizu-3.jpg": "179f9ca0cb",
  "./img/activities/kiyomizu.jpg": "e893960265",
  "./img/activities/kofukuji-2.jpg": "ac7d90dccc",
  "./img/activities/kofukuji-3.jpg": "b7a7c75445",
  "./img/activities/kofukuji.jpg": "904d2208d6",
  "./img/activities/kuromon-2.jpg": "ddaf95e89c",
  "./img/activities/kuromon-3.jpg": "0950ee86c5",
  "./img/activities/kuromon.jpg": "de89994c7b",
  "./img/activities/meiji-2.jpg": "e5327b3818",
  "./img/activities/meiji-3.jpg": "e4ab98bd7a",
  "./img/activities/meiji.jpg": "e78209af07",
  "./img/activities/miyagawa-2.jpg": "c36c4f2810",
  "./img/activities/miyagawa-3.jpg": "f877b12e20",
  "./img/activities/miyagawa.jpg": "7ec9e162bd",
  "./img/activities/momiji.jpg": "84950ce321",
  "./img/activities/music-forest-2.jpg": "b0096886e0",
  "./img/activities/music-forest-3.jpg": "c6f5147b7a",
  "./img/activities/music-forest.jpg": "8b543886a0",
  "./img/activities/myoryuji.jpg": "202a50a79f",
  "./img/activities/nagamachi-2.jpg": "719abdd63a",
  "./img/activities/nagamachi-3.jpg": "595c5ddfc6",
  "./img/activities/nagamachi.jpg": "adf9c09120",
  "./img/activities/namba-yasaka-2.jpg": "49c14e79d9",
  "./img/activities/namba-yasaka-3.jpg": "2f45207612",
  "./img/activities/namba-yasaka.jpg": "7d060c431b",
  "./img/activities/nara-park-2.jpg": "52dad0d79e",
  "./img/activities/nara-park-3.jpg": "0016d6b027",
  "./img/activities/nara-park.jpg": "ac20412499",
  "./img/activities/nijo-2.jpg": "e1c3b7c89d",
  "./img/activities/nijo-3.jpg": "5f625f2f95",
  "./img/activities/nijo.jpg": "c38eedf613",
  "./img/activities/nishi-chaya-2.jpg": "2ec7167ea4",
  "./img/activities/nishi-chaya-3.jpg": "2aa9fa4536",
  "./img/activities/nishi-chaya.jpg": "ea35cdab74",
  "./img/activities/nishiki-2.jpg": "67a69ad3f9",
  "./img/activities/nishiki-3.jpg": "c42966b034",
  "./img/activities/nishiki.jpg": "a76f7c29e6",
  "./img/activities/odaiba-2.jpg": "d964631de4",
  "./img/activities/odaiba-3.jpg": "6e66b959a0",
  "./img/activities/odaiba.jpg": "6138e2f508",
  "./img/activities/omicho-2.jpg": "d792d7bf83",
  "./img/activities/omicho-3.jpg": "04d15cf061",
  "./img/activities/omicho.jpg": "91691c4940",
  "./img/activities/osaka-castle-2.jpg": "911508c267",
  "./img/activities/osaka-castle-3.jpg": "5d1bd3d8f8",
  "./img/activities/osaka-castle.jpg": "e60f7f6e75",
  "./img/activities/oshino-2.jpg": "f126a12163",
  "./img/activities/oshino-3.jpg": "97c57cdb65",
  "./img/activities/oshino.jpg": "9b40044b31",
  "./img/activities/oyama-2.jpg": "3f5a92dc09",
  "./img/activities/oyama-3.jpg": "5dcd0dd832",
  "./img/activities/oyama.jpg": "4c9faf617b",
  "./img/activities/philosopher-2.jpg": "51627b2bff",
  "./img/activities/philosopher-3.jpg": "3a13f2f806",
  "./img/activities/philosopher.jpg": "56d23d2817",
  "./img/activities/pontocho-2.jpg": "d283f59758",
  "./img/activities/pontocho-3.jpg": "f55f39a867",
  "./img/activities/pontocho.jpg": "51501e84e8",
  "./img/activities/ropeway-2.jpg": "999fe138e0",
  "./img/activities/ropeway-3.jpg": "b27db27e99",
  "./img/activities/ropeway.jpg": "0d584aa3d4",
  "./img/activities/saiko-2.jpg": "5f7b502a5c",
  "./img/activities/saiko-3.jpg": "c75221f908",
  "./img/activities/saiko.jpg": "a6c1b4f9d1",
  "./img/activities/sanmachi-2.jpg": "2858d9c2fc",
  "./img/activities/sanmachi.jpg": "75da431fad",
  "./img/activities/sensoji-2.jpg": "682502237c",
  "./img/activities/sensoji-3.jpg": "dbb1856eb1",
  "./img/activities/sensoji.jpg": "e4ee09969c",
  "./img/activities/shibuya-2.jpg": "117c48c23c",
  "./img/activities/shibuya-3.jpg": "33b96ae021",
  "./img/activities/shibuya.jpg": "93b4a19590",
  "./img/activities/shinjuku-2.jpg": "56a2c773c8",
  "./img/activities/shinjuku-3.jpg": "ebe512ac49",
  "./img/activities/shinjuku.jpg": "6c76f569d8",
  "./img/activities/shinsaibashi-2.jpg": "2d20ea3a7b",
  "./img/activities/shinsaibashi-3.jpg": "591f1efe38",
  "./img/activities/shinsaibashi.jpg": "fa9ecc0fe1",
  "./img/activities/shinsekai-2.jpg": "be5b167dba",
  "./img/activities/shinsekai.jpg": "ae0d5504a2",
  "./img/activities/shirakawa-2.jpg": "e14f84da0d",
  "./img/activities/shirakawa-3.jpg": "554bcc1d4b",
  "./img/activities/shirakawa.jpg": "4c668fe350",
  "./img/activities/sumida-2.jpg": "9224d7cc5f",
  "./img/activities/sumida-3.jpg": "914ea95dd1",
  "./img/activities/sumida.jpg": "89ee06218e",
  "./img/activities/tea-2.jpg": "39fa5c7283",
  "./img/activities/tea-3.jpg": "9e3c54ef20",
  "./img/activities/tea.jpg": "cffb33262b",
  "./img/activities/teamlab-2.jpg": "0911e37ffa",
  "./img/activities/teamlab-3.jpg": "3cb1160a7d",
  "./img/activities/teamlab.jpg": "646c89ff68",
  "./img/activities/teramachi.jpg": "87b2ee2595",
  "./img/activities/thumb/akihabara-2.jpg": "425e2c54c6",
  "./img/activities/thumb/akihabara-3.jpg": "f1b7c74a21",
  "./img/activities/thumb/akihabara.jpg": "27afc52513",
  "./img/activities/thumb/animate.jpg": "002e88f4e1",
  "./img/activities/thumb/arashiyama-2.jpg": "00b2ecd271",
  "./img/activities/thumb/arashiyama-3.jpg": "3dd8578d60",
  "./img/activities/thumb/arashiyama.jpg": "3026a17dfc",
  "./img/activities/thumb/character-street-2.jpg": "c96eb5f99a",
  "./img/activities/thumb/character-street-3.jpg": "050585d478",
  "./img/activities/thumb/character-street.jpg": "922eb77ca0",
  "./img/activities/thumb/chureito-2.jpg": "eba5c9a72a",
  "./img/activities/thumb/chureito-3.jpg": "bfd09a298e",
  "./img/activities/thumb/chureito.jpg": "1c6fc0bf0a",
  "./img/activities/thumb/daigo-2.jpg": "f4acc3884e",
  "./img/activities/thumb/daigo-3.jpg": "9143b5951e",
  "./img/activities/thumb/daigo.jpg": "8ec4484d2e",
  "./img/activities/thumb/denden-2.jpg": "919c016595",
  "./img/activities/thumb/denden.jpg": "1067ad8035",
  "./img/activities/thumb/dotonbori-2.jpg": "68b3403855",
  "./img/activities/thumb/dotonbori-3.jpg": "be3f75da5a",
  "./img/activities/thumb/dotonbori.jpg": "3379be1071",
  "./img/activities/thumb/fujiq-2.jpg": "2527d9147a",
  "./img/activities/thumb/fujiq-3.jpg": "dd98ea04a4",
  "./img/activities/thumb/fujiq.jpg": "c55dccb222",
  "./img/activities/thumb/fushimi-2.jpg": "6c21e1316b",
  "./img/activities/thumb/fushimi-3.jpg": "6c3e71a60f",
  "./img/activities/thumb/fushimi.jpg": "f72e90ce94",
  "./img/activities/thumb/ginza-2.jpg": "a3e452ae6a",
  "./img/activities/thumb/ginza-3.jpg": "1f9b25f8c0",
  "./img/activities/thumb/ginza.jpg": "da696df39d",
  "./img/activities/thumb/gold-leaf-2.jpg": "ed4838aba4",
  "./img/activities/thumb/gold-leaf.jpg": "4e3a079f24",
  "./img/activities/thumb/harajuku-2.jpg": "19eebf0c89",
  "./img/activities/thumb/harajuku-3.jpg": "70f41447b4",
  "./img/activities/thumb/harajuku.jpg": "c6114705b1",
  "./img/activities/thumb/higashi-chaya-2.jpg": "9451104a47",
  "./img/activities/thumb/higashi-chaya-3.jpg": "3316b5d4cb",
  "./img/activities/thumb/higashi-chaya.jpg": "b55ca5b098",
  "./img/activities/thumb/hozenji-2.jpg": "43e6dff518",
  "./img/activities/thumb/hozenji-3.jpg": "36fc565bbf",
  "./img/activities/thumb/hozenji.jpg": "7772f19a10",
  "./img/activities/thumb/imperial-2.jpg": "c9ac439bbf",
  "./img/activities/thumb/imperial-3.jpg": "db6cde3a91",
  "./img/activities/thumb/imperial.jpg": "4af33d73ac",
  "./img/activities/thumb/itchiku-2.jpg": "4691367ced",
  "./img/activities/thumb/itchiku-3.jpg": "3d6b7ba712",
  "./img/activities/thumb/itchiku.jpg": "7ed2ce5c26",
  "./img/activities/thumb/jinya-2.jpg": "1726ec98e6",
  "./img/activities/thumb/jinya-3.jpg": "b48bfac63f",
  "./img/activities/thumb/jinya.jpg": "79548fffe5",
  "./img/activities/thumb/kanazawa-castle-2.jpg": "dbc43039c6",
  "./img/activities/thumb/kanazawa-castle-3.jpg": "62e0d97dcd",
  "./img/activities/thumb/kanazawa-castle.jpg": "d9a1701b1c",
  "./img/activities/thumb/kanazawa-museum-2.jpg": "3f9433acc0",
  "./img/activities/thumb/kanazawa-museum-3.jpg": "cea4e7d8ff",
  "./img/activities/thumb/kanazawa-museum.jpg": "d2d8f6fa67",
  "./img/activities/thumb/kasuga-2.jpg": "7640abd2c5",
  "./img/activities/thumb/kasuga-3.jpg": "ecbe1e46ed",
  "./img/activities/thumb/kasuga.jpg": "24ce8bda9d",
  "./img/activities/thumb/kawaguchi-2.jpg": "61ad9f9424",
  "./img/activities/thumb/kawaguchi-3.jpg": "eb849a1b32",
  "./img/activities/thumb/kawaguchi.jpg": "13e7c0c1a7",
  "./img/activities/thumb/kenrokuen-2.jpg": "a2b7348027",
  "./img/activities/thumb/kenrokuen-3.jpg": "4052899561",
  "./img/activities/thumb/kenrokuen.jpg": "3f29df83f9",
  "./img/activities/thumb/kinkakuji-2.jpg": "50e92ba175",
  "./img/activities/thumb/kinkakuji-3.jpg": "ca6fafcc9f",
  "./img/activities/thumb/kinkakuji.jpg": "94ab82decd",
  "./img/activities/thumb/kiyomizu-2.jpg": "7c090d58d1",
  "./img/activities/thumb/kiyomizu-3.jpg": "7d10bcb0fa",
  "./img/activities/thumb/kiyomizu.jpg": "4fcbf84dbe",
  "./img/activities/thumb/kofukuji-2.jpg": "15f5cf7832",
  "./img/activities/thumb/kofukuji-3.jpg": "c277d685f9",
  "./img/activities/thumb/kofukuji.jpg": "f69a6b4a5c",
  "./img/activities/thumb/kuromon-2.jpg": "557dbc241c",
  "./img/activities/thumb/kuromon-3.jpg": "82a403cd79",
  "./img/activities/thumb/kuromon.jpg": "e8ff2174a9",
  "./img/activities/thumb/meiji-2.jpg": "c8abe50597",
  "./img/activities/thumb/meiji-3.jpg": "b4587ec128",
  "./img/activities/thumb/meiji.jpg": "77c5f07f4a",
  "./img/activities/thumb/miyagawa-2.jpg": "831071bd4b",
  "./img/activities/thumb/miyagawa-3.jpg": "ef97b36061",
  "./img/activities/thumb/miyagawa.jpg": "43fb284903",
  "./img/activities/thumb/momiji.jpg": "acdc34d004",
  "./img/activities/thumb/music-forest-2.jpg": "efff2981c4",
  "./img/activities/thumb/music-forest-3.jpg": "3feba10cac",
  "./img/activities/thumb/music-forest.jpg": "ddc8c46872",
  "./img/activities/thumb/myoryuji.jpg": "a5d93a161b",
  "./img/activities/thumb/nagamachi-2.jpg": "ba59b32b46",
  "./img/activities/thumb/nagamachi-3.jpg": "9922d6a5c7",
  "./img/activities/thumb/nagamachi.jpg": "ca0ac7c2f3",
  "./img/activities/thumb/namba-yasaka-2.jpg": "6af703e4b0",
  "./img/activities/thumb/namba-yasaka-3.jpg": "01427e6430",
  "./img/activities/thumb/namba-yasaka.jpg": "a3f967c640",
  "./img/activities/thumb/nara-park-2.jpg": "6cf0bfeb9a",
  "./img/activities/thumb/nara-park-3.jpg": "70adccae01",
  "./img/activities/thumb/nara-park.jpg": "f3c423fa2d",
  "./img/activities/thumb/nijo-2.jpg": "c6b6d9cc7a",
  "./img/activities/thumb/nijo-3.jpg": "f950363a4a",
  "./img/activities/thumb/nijo.jpg": "3aec5b62fa",
  "./img/activities/thumb/nishi-chaya-2.jpg": "8d8842d661",
  "./img/activities/thumb/nishi-chaya-3.jpg": "e43c10fe3d",
  "./img/activities/thumb/nishi-chaya.jpg": "842d27b601",
  "./img/activities/thumb/nishiki-2.jpg": "55de61c024",
  "./img/activities/thumb/nishiki-3.jpg": "7004ad13ad",
  "./img/activities/thumb/nishiki.jpg": "a56c97ce8b",
  "./img/activities/thumb/odaiba-2.jpg": "4cad4f29de",
  "./img/activities/thumb/odaiba-3.jpg": "e216f528ad",
  "./img/activities/thumb/odaiba.jpg": "d5a144a10c",
  "./img/activities/thumb/omicho-2.jpg": "f9ea87191b",
  "./img/activities/thumb/omicho-3.jpg": "d139280a2c",
  "./img/activities/thumb/omicho.jpg": "f524454199",
  "./img/activities/thumb/osaka-castle-2.jpg": "64c7e9236b",
  "./img/activities/thumb/osaka-castle-3.jpg": "3e950c6527",
  "./img/activities/thumb/osaka-castle.jpg": "b1465ef48b",
  "./img/activities/thumb/oshino-2.jpg": "6e790a68e6",
  "./img/activities/thumb/oshino-3.jpg": "5031f9aab3",
  "./img/activities/thumb/oshino.jpg": "79ff465694",
  "./img/activities/thumb/oyama-2.jpg": "6aa105b5aa",
  "./img/activities/thumb/oyama-3.jpg": "5513b0eda0",
  "./img/activities/thumb/oyama.jpg": "4f7de0854a",
  "./img/activities/thumb/philosopher-2.jpg": "40794aebaa",
  "./img/activities/thumb/philosopher-3.jpg": "066e2e4de4",
  "./img/activities/thumb/philosopher.jpg": "cd4ecec693",
  "./img/activities/thumb/pontocho-2.jpg": "e1582da76d",
  "./img/activities/thumb/pontocho-3.jpg": "b4e1f052e2",
  "./img/activities/thumb/pontocho.jpg": "a2bbc00b4b",
  "./img/activities/thumb/ropeway-2.jpg": "6643d551f7",
  "./img/activities/thumb/ropeway-3.jpg": "4a703a2663",
  "./img/activities/thumb/ropeway.jpg": "5870d11fe0",
  "./img/activities/thumb/saiko-2.jpg": "23f3219fd4",
  "./img/activities/thumb/saiko-3.jpg": "1619be05bb",
  "./img/activities/thumb/saiko.jpg": "601580ca94",
  "./img/activities/thumb/sanmachi-2.jpg": "69c6735425",
  "./img/activities/thumb/sanmachi.jpg": "cdfe814496",
  "./img/activities/thumb/sensoji-2.jpg": "8c61776d7e",
  "./img/activities/thumb/sensoji-3.jpg": "22c4c91081",
  "./img/activities/thumb/sensoji.jpg": "ca690b33d3",
  "./img/activities/thumb/shibuya-2.jpg": "079ba1400c",
  "./img/activities/thumb/shibuya-3.jpg": "ef7ce19330",
  "./img/activities/thumb/shibuya.jpg": "c411560f37",
  "./img/activities/thumb/shinjuku-2.jpg": "b4255df57d",
  "./img/activities/thumb/shinjuku-3.jpg": "9496abd357",
  "./img/activities/thumb/shinjuku.jpg": "0f76496beb",
  "./img/activities/thumb/shinsaibashi-2.jpg": "54c63e4d8e",
  "./img/activities/thumb/shinsaibashi-3.jpg": "d424f207d8",
  "./img/activities/thumb/shinsaibashi.jpg": "7a70fd7147",
  "./img/activities/thumb/shinsekai-2.jpg": "4c5234681a",
  "./img/activities/thumb/shinsekai.jpg": "f1676a82ac",
  "./img/activities/thumb/shirakawa-2.jpg": "d1511b2491",
  "./img/activities/thumb/shirakawa-3.jpg": "646ce4073c",
  "./img/activities/thumb/shirakawa.jpg": "d4edb446f2",
  "./img/activities/thumb/sumida-2.jpg": "1954592cb1",
  "./img/activities/thumb/sumida-3.jpg": "1b031e20cc",
  "./img/activities/thumb/sumida.jpg": "cd5b9aa8da",
  "./img/activities/thumb/tea-2.jpg": "624fe492a7",
  "./img/activities/thumb/tea-3.jpg": "e7f06e34b3",
  "./img/activities/thumb/tea.jpg": "24c18297e2",
  "./img/activities/thumb/teamlab-2.jpg": "53c04df0f7",
  "./img/activities/thumb/teamlab-3.jpg": "d746264a56",
  "./img/activities/thumb/teamlab.jpg": "04d93d95e5",
  "./img/activities/thumb/teramachi.jpg": "30d9d52150",
  "./img/activities/thumb/todaiji-2.jpg": "1ea7ba7511",
  "./img/activities/thumb/todaiji-3.jpg": "5188e7a434",
  "./img/activities/thumb/todaiji.jpg": "6620bfbc3d",
  "./img/activities/thumb/tokyo-tower-2.jpg": "086a9cd1c9",
  "./img/activities/thumb/tokyo-tower-3.jpg": "a7ef81493a",
  "./img/activities/thumb/tokyo-tower.jpg": "6ab99629d2",
  "./img/activities/thumb/ueno-2.jpg": "e2d6b34761",
  "./img/activities/thumb/ueno-3.jpg": "b944368300",
  "./img/activities/thumb/ueno.jpg": "6b52f31578",
  "./img/activities/thumb/usj-2.jpg": "e900c11254",
  "./img/activities/thumb/usj-3.jpg": "ef18a6e3f2",
  "./img/activities/thumb/usj.jpg": "5df6d0eb58",
  "./img/activities/thumb/wagashi-2.jpg": "3c55e01b00",
  "./img/activities/thumb/wagashi-3.jpg": "78c004c3d6",
  "./img/activities/thumb/wagashi.jpg": "1359a872b2",
  "./img/activities/thumb/yanaka-2.jpg": "1918fc7069",
  "./img/activities/thumb/yanaka-3.jpg": "6db76a2882",
  "./img/activities/thumb/yanaka.jpg": "0d5ef7f52c",
  "./img/activities/thumb/yasaka-2.jpg": "7a2d1aaec8",
  "./img/activities/thumb/yasaka-3.jpg": "e4688a28ce",
  "./img/activities/thumb/yasaka.jpg": "afca975a64",
  "./img/activities/todaiji-2.jpg": "e1c9a1850f",
  "./img/activities/todaiji-3.jpg": "4eaee0125b",
  "./img/activities/todaiji.jpg": "2bf868ab92",
  "./img/activities/tokyo-tower-2.jpg": "94a91466bc",
  "./img/activities/tokyo-tower-3.jpg": "4fa76385d4",
  "./img/activities/tokyo-tower.jpg": "fa8fc004df",
  "./img/activities/ueno-2.jpg": "c1fb569543",
  "./img/activities/ueno-3.jpg": "cd1d1576fb",
  "./img/activities/ueno.jpg": "db467be96e",
  "./img/activities/usj-2.jpg": "c7dbc9228f",
  "./img/activities/usj-3.jpg": "05c32a6c58",
  "./img/activities/usj.jpg": "d01d245902",
  "./img/activities/wagashi-2.jpg": "3f5f6d3d30",
  "./img/activities/wagashi-3.jpg": "cb786b7d16",
  "./img/activities/wagashi.jpg": "ed526686f9",
  "./img/activities/yanaka-2.jpg": "feb15c2e05",
  "./img/activities/yanaka-3.jpg": "d929b6ccb1",
  "./img/activities/yanaka.jpg": "71dc623f1f",
  "./img/activities/yasaka-2.jpg": "c1158c31a5",
  "./img/activities/yasaka-3.jpg": "d1be6e4643",
  "./img/activities/yasaka.jpg": "3e4f3ceb63",
  "./img/hotels/agora-kyoto-2.jpg": "bf44e912bd",
  "./img/hotels/agora-kyoto-3.jpg": "ad94b19a65",
  "./img/hotels/agora-kyoto-4.jpg": "eb45642904",
  "./img/hotels/agora-kyoto.jpg": "25964d77b6",
  "./img/hotels/deer-park-nara-2.jpg": "5b9cdc02d5",
  "./img/hotels/deer-park-nara-3.jpg": "7ff33d4d01",
  "./img/hotels/deer-park-nara-4.jpg": "0c883ffda0",
  "./img/hotels/deer-park-nara.jpg": "029f678a2b",
  "./img/hotels/garner-osaka-2.jpg": "54116fc63a",
  "./img/hotels/garner-osaka-3.jpg": "11028315de",
  "./img/hotels/garner-osaka-4.jpg": "49fadb9d9d",
  "./img/hotels/garner-osaka.jpg": "a60b493076",
  "./img/hotels/henn-na-kanazawa-2.jpg": "4ecda54b44",
  "./img/hotels/henn-na-kanazawa-3.jpg": "09f3259edb",
  "./img/hotels/henn-na-kanazawa-4.jpg": "88e9af110c",
  "./img/hotels/henn-na-kanazawa.jpg": "c62a658a2f",
  "./img/hotels/homenest-akihabara-2.jpg": "8593727b98",
  "./img/hotels/homenest-akihabara-3.jpg": "ddf9985175",
  "./img/hotels/homenest-akihabara-4.jpg": "3ec0a1a0da",
  "./img/hotels/homenest-akihabara-5.jpg": "0969a4c606",
  "./img/hotels/homenest-akihabara-6.jpg": "a7ca2f7433",
  "./img/hotels/homenest-akihabara.jpg": "5f8747d525",
  "./img/hotels/kawaguchiko-2.jpg": "949760caed",
  "./img/hotels/kawaguchiko-3.jpg": "82037b94cd",
  "./img/hotels/kawaguchiko-4.jpg": "a36964d161",
  "./img/hotels/kawaguchiko.jpg": "a3db78613d",
  "./img/hotels/mercure-takayama-2.jpg": "e77ed8954c",
  "./img/hotels/mercure-takayama-3.jpg": "5c4a6ca7ba",
  "./img/hotels/mercure-takayama-4.jpg": "544d42c323",
  "./img/hotels/mercure-takayama.jpg": "1293a45637",
  "./img/hotels/royal-park-haneda-2.jpg": "a77f626083",
  "./img/hotels/royal-park-haneda-3.jpg": "cd314f5672",
  "./img/hotels/royal-park-haneda-4.jpg": "130a4ae94d",
  "./img/hotels/royal-park-haneda.jpg": "336889bd28",
  "./img/hotels/thumb/agora-kyoto-2.jpg": "88a6fa86f2",
  "./img/hotels/thumb/agora-kyoto-3.jpg": "43bfbbb5af",
  "./img/hotels/thumb/agora-kyoto-4.jpg": "ee0f191d3f",
  "./img/hotels/thumb/agora-kyoto.jpg": "d27a83e11f",
  "./img/hotels/thumb/deer-park-nara-2.jpg": "a4453b4c8b",
  "./img/hotels/thumb/deer-park-nara-3.jpg": "ea6efab24f",
  "./img/hotels/thumb/deer-park-nara-4.jpg": "e23c09cee7",
  "./img/hotels/thumb/deer-park-nara.jpg": "4d44828a83",
  "./img/hotels/thumb/garner-osaka-2.jpg": "f7bb953403",
  "./img/hotels/thumb/garner-osaka-3.jpg": "e5e748cb4b",
  "./img/hotels/thumb/garner-osaka-4.jpg": "15ac663ba4",
  "./img/hotels/thumb/garner-osaka.jpg": "121f8b3d7d",
  "./img/hotels/thumb/henn-na-kanazawa-2.jpg": "eb9a20a3ef",
  "./img/hotels/thumb/henn-na-kanazawa-3.jpg": "245f0c775a",
  "./img/hotels/thumb/henn-na-kanazawa-4.jpg": "8778016ea4",
  "./img/hotels/thumb/henn-na-kanazawa.jpg": "7302f95b8e",
  "./img/hotels/thumb/homenest-akihabara-2.jpg": "f8700d37ed",
  "./img/hotels/thumb/homenest-akihabara-3.jpg": "211ebaa2be",
  "./img/hotels/thumb/homenest-akihabara-4.jpg": "23b4d3b26e",
  "./img/hotels/thumb/homenest-akihabara-5.jpg": "887adeb0b7",
  "./img/hotels/thumb/homenest-akihabara-6.jpg": "7678b0a836",
  "./img/hotels/thumb/homenest-akihabara.jpg": "34749f1a6c",
  "./img/hotels/thumb/kawaguchiko-2.jpg": "0baa0d76b3",
  "./img/hotels/thumb/kawaguchiko-3.jpg": "0f47d8f622",
  "./img/hotels/thumb/kawaguchiko-4.jpg": "1b3617f644",
  "./img/hotels/thumb/kawaguchiko.jpg": "e31f9a3e89",
  "./img/hotels/thumb/mercure-takayama-2.jpg": "40df8b5eda",
  "./img/hotels/thumb/mercure-takayama-3.jpg": "b1e13dd17d",
  "./img/hotels/thumb/mercure-takayama-4.jpg": "59eada56ab",
  "./img/hotels/thumb/mercure-takayama.jpg": "48bf8fb5b3",
  "./img/hotels/thumb/royal-park-haneda-2.jpg": "27e39feed5",
  "./img/hotels/thumb/royal-park-haneda-3.jpg": "52fd523bb7",
  "./img/hotels/thumb/royal-park-haneda-4.jpg": "788bb9a3b2",
  "./img/hotels/thumb/royal-park-haneda.jpg": "6fd99cf995",
  "./img/icon-180.png": "61ef11573b",
  "./img/icon-192.png": "1cd8513e28",
  "./img/icon-512.png": "d22fb99cd0",
  "./img/logo.svg": "05a44a04b4"
};
// </precache>

async function putFresh(cache, url) {
  const res = await fetch(url, { cache: "reload" });
  if (!res || !res.ok) return;
  const hash = IMG_HASH[url];
  await cache.put(url, hash ? await stamped(res, hash) : res.clone());
}

/** Copie de la réponse marquée de l’empreinte de son contenu (en-tête x-img-hash). */
async function stamped(res, hash) {
  const headers = new Headers(res.headers);
  headers.set("x-img-hash", hash);
  return new Response(await res.clone().blob(), { status: res.status, statusText: res.statusText, headers });
}

async function sha1Short(blob) {
  const buf = await crypto.subtle.digest("SHA-1", await blob.arrayBuffer());
  return Array.from(new Uint8Array(buf), (b) => b.toString(16).padStart(2, "0")).join("").slice(0, 10);
}

/**
 * Image absente ou modifiée depuis sa mise en cache ? (le cache des images est conservé
 * entre les versions : sans ce contrôle, un fichier remplacé sous le même nom resterait figé).
 * Entrée d’avant l’empreinte : on compare le contenu, et on la marque si elle est à jour.
 */
async function isStale(cache, url) {
  const want = IMG_HASH[url];
  const cached = await cache.match(url);
  if (!cached) return true;
  if (!want) return false;
  const have = cached.headers.get("x-img-hash");
  if (have) return have !== want;
  try {
    if ((await sha1Short(await cached.clone().blob())) !== want) return true;
    await cache.put(url, await stamped(cached, want));
  } catch (_) { /* contrôle impossible : on garde l’image */ }
  return false;
}

/** Exécute `task` sur chaque élément, `n` à la fois (une erreur isolée n’arrête rien). */
async function eachParallel(list, n, task) {
  let i = 0;
  const worker = async () => {
    while (i < list.length) {
      const item = list[i++];
      try { await task(item); } catch (_) { /* un échec isolé n’empêche pas l’installation */ }
    }
  };
  await Promise.all(Array.from({ length: n }, worker));
}

self.addEventListener("install", (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    const imgCache = await caches.open(IMG_CACHE);
    // Code, données, vignettes, logo et icônes seulement (≈ 3 Mo d’images) : la mise à jour ne les attend pas
    await eachParallel(ASSETS.filter((u) => !isImage(u)), 6, (url) => putFresh(cache, url));
    await eachParallel(ASSETS.filter((u) => isImage(u) && !isFullPhoto(u)), 6, async (url) => {
      if (await isStale(imgCache, url)) await putFresh(imgCache, url);
    });
    await self.skipWaiting();
  })());
});

/** Photos complètes manquantes, 2 à la fois (laisse la bande passante à ce qui s’affiche). */
async function precacheFullPhotos() {
  const imgCache = await caches.open(IMG_CACHE);
  await eachParallel(ASSETS.filter(isFullPhoto), 2, async (url) => {
    if (await isStale(imgCache, url)) await putFresh(imgCache, url);
  });
}
let photosRun = null;

self.addEventListener("activate", (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((k) => k !== CACHE && k !== TILE_CACHE && k !== IMG_CACHE).map((k) => caches.delete(k)));
    // Ménage : photos retirées du site
    const wanted = new Set(ASSETS.filter(isImage).map((u) => new URL(u, self.location).href));
    const imgCache = await caches.open(IMG_CACHE);
    const stored = await imgCache.keys();
    await Promise.all(stored.filter((r) => !wanted.has(r.url.split("?")[0])).map((r) => imgCache.delete(r)));
    await self.clients.claim();
  })());
});

self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") self.skipWaiting();
  if (event.data && event.data.type === "PRECACHE_IMAGES") {
    if (!photosRun) photosRun = precacheFullPhotos().finally(() => { photosRun = null; });
    event.waitUntil(photosRun);
  }
});

function fetchWithTimeout(req, ms) {
  return Promise.race([
    fetch(req, { cache: "no-store" }),
    new Promise((_, reject) => setTimeout(() => reject(new Error("timeout")), ms))
  ]);
}

async function fallbackPage() {
  return (await caches.match("./index.html")) || (await caches.match("./")) || Response.error();
}

/** Réseau d’abord (avec délai max), copie en cache, sinon version en cache. */
async function networkFirst(req, isPage) {
  try {
    const res = await fetchWithTimeout(req, NETWORK_TIMEOUT_MS);
    if (res && res.ok) {
      const cache = await caches.open(CACHE);
      try { await cache.put(req, res.clone()); } catch (_) { /* quota */ }
    }
    return res;
  } catch (_) {
    const cached = await caches.match(req, { ignoreSearch: true });
    if (cached) return cached;
    return isPage ? fallbackPage() : Response.error();
  }
}

/** Cache d’abord, réseau sinon (et mise en cache — photos dans IMG_CACHE). */
async function cacheFirst(req) {
  const cached = await caches.match(req, { ignoreSearch: true });
  if (cached) return cached;
  try {
    const res = await fetch(req);
    if (res && res.ok) {
      const cache = await caches.open(isImage(new URL(req.url).pathname) ? IMG_CACHE : CACHE);
      cache.put(req, res.clone());
    }
    return res;
  } catch (_) {
    return fallbackPage();
  }
}

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  const path = url.pathname;
  const isPage = req.mode === "navigate" || path.endsWith("/") || path.endsWith("/index.html");
  const isLib = path.includes("/lib/");
  const isApp = !isLib && (
    path.endsWith("sw.js") ||
    path.includes("/src/") ||
    path.includes("/styles/") ||
    path.includes("/data/"));

  event.respondWith(isPage || isApp ? networkFirst(req, isPage) : cacheFirst(req));
});
