/* Service worker — cache hors ligne (1re visite en Wi‑Fi, puis utilisable sans réseau dans Safari).
   - Code, styles, données : réseau d’abord (mises à jour immédiates), cache si hors ligne / lent.
   - Librairie MapLibre et images : cache d’abord ; les images vivent dans IMG_CACHE, conservé entre
     les versions. Installation = vignettes seulement ; photos complètes en tâche de fond quand la page
     envoie PRECACHE_IMAGES (2 à la fois, seules les manquantes ou modifiées : empreinte IMG_HASH).
   - Tuiles de carte : cache séparé TILE_CACHE, géré par src/map/offline-tiles.js, jamais purgé ici.
   Version : scripts/bump-version.mjs · liste ASSETS : scripts/gen-precache.mjs. */
const CACHE = "japan-trip-2026-v183";
const TILE_CACHE = "japan-tiles-v1";
/** Photos : cache gardé d’une version à l’autre (seules les nouvelles sont téléchargées). */
const IMG_CACHE = "japan-img-v1";
const isImage = (url) => url.includes("/img/");
/** Photo complète (≈ 230 Ko) : préchargée en tâche de fond, pas à l’installation. Les vignettes (thumb/) si. */
const isFullPhoto = (url) => /\/img\/(activities|hotels)\/[^/]+$/.test(url);
const NETWORK_TIMEOUT_MS = 4000;

// <precache> — généré par scripts/gen-precache.mjs, ne pas éditer à la main
const ASSETS = [
  "./",
  "./index.html",
  "./manifest.webmanifest",
  "./sw.js",
  "./data/cities.json",
  "./data/days.json",
  "./data/journeys.json",
  "./data/legs.json",
  "./data/photos.json",
  "./data/phrases.json",
  "./data/places-meta.json",
  "./data/practical.json",
  "./data/prep.json",
  "./data/trip.json",
  "./img/activities/akihabara-2.jpg",
  "./img/activities/akihabara-3.jpg",
  "./img/activities/akihabara.jpg",
  "./img/activities/animate.jpg",
  "./img/activities/arashiyama-2.jpg",
  "./img/activities/arashiyama-3.jpg",
  "./img/activities/arashiyama.jpg",
  "./img/activities/character-street-2.jpg",
  "./img/activities/character-street-3.jpg",
  "./img/activities/character-street.jpg",
  "./img/activities/chureito-2.jpg",
  "./img/activities/chureito-3.jpg",
  "./img/activities/chureito.jpg",
  "./img/activities/daigo-2.jpg",
  "./img/activities/daigo-3.jpg",
  "./img/activities/daigo.jpg",
  "./img/activities/denden-2.jpg",
  "./img/activities/denden.jpg",
  "./img/activities/dotonbori-2.jpg",
  "./img/activities/dotonbori-3.jpg",
  "./img/activities/dotonbori.jpg",
  "./img/activities/fujiq-2.jpg",
  "./img/activities/fujiq-3.jpg",
  "./img/activities/fujiq.jpg",
  "./img/activities/fushimi-2.jpg",
  "./img/activities/fushimi-3.jpg",
  "./img/activities/fushimi.jpg",
  "./img/activities/ginza-2.jpg",
  "./img/activities/ginza-3.jpg",
  "./img/activities/ginza.jpg",
  "./img/activities/gold-leaf-2.jpg",
  "./img/activities/gold-leaf.jpg",
  "./img/activities/harajuku-2.jpg",
  "./img/activities/harajuku-3.jpg",
  "./img/activities/harajuku.jpg",
  "./img/activities/higashi-chaya-2.jpg",
  "./img/activities/higashi-chaya-3.jpg",
  "./img/activities/higashi-chaya.jpg",
  "./img/activities/hozenji-2.jpg",
  "./img/activities/hozenji-3.jpg",
  "./img/activities/hozenji.jpg",
  "./img/activities/imperial-2.jpg",
  "./img/activities/imperial-3.jpg",
  "./img/activities/imperial.jpg",
  "./img/activities/itchiku-2.jpg",
  "./img/activities/itchiku-3.jpg",
  "./img/activities/itchiku.jpg",
  "./img/activities/jinya-2.jpg",
  "./img/activities/jinya-3.jpg",
  "./img/activities/jinya.jpg",
  "./img/activities/kanazawa-castle-2.jpg",
  "./img/activities/kanazawa-castle-3.jpg",
  "./img/activities/kanazawa-castle.jpg",
  "./img/activities/kanazawa-museum-2.jpg",
  "./img/activities/kanazawa-museum-3.jpg",
  "./img/activities/kanazawa-museum.jpg",
  "./img/activities/kasuga-2.jpg",
  "./img/activities/kasuga-3.jpg",
  "./img/activities/kasuga.jpg",
  "./img/activities/kawaguchi-2.jpg",
  "./img/activities/kawaguchi-3.jpg",
  "./img/activities/kawaguchi.jpg",
  "./img/activities/kenrokuen-2.jpg",
  "./img/activities/kenrokuen-3.jpg",
  "./img/activities/kenrokuen.jpg",
  "./img/activities/kinkakuji-2.jpg",
  "./img/activities/kinkakuji-3.jpg",
  "./img/activities/kinkakuji.jpg",
  "./img/activities/kiyomizu-2.jpg",
  "./img/activities/kiyomizu-3.jpg",
  "./img/activities/kiyomizu.jpg",
  "./img/activities/kofukuji-2.jpg",
  "./img/activities/kofukuji-3.jpg",
  "./img/activities/kofukuji.jpg",
  "./img/activities/kuromon-2.jpg",
  "./img/activities/kuromon-3.jpg",
  "./img/activities/kuromon.jpg",
  "./img/activities/meiji-2.jpg",
  "./img/activities/meiji-3.jpg",
  "./img/activities/meiji.jpg",
  "./img/activities/miyagawa-2.jpg",
  "./img/activities/miyagawa-3.jpg",
  "./img/activities/miyagawa.jpg",
  "./img/activities/momiji.jpg",
  "./img/activities/music-forest-2.jpg",
  "./img/activities/music-forest-3.jpg",
  "./img/activities/music-forest.jpg",
  "./img/activities/myoryuji.jpg",
  "./img/activities/nagamachi-2.jpg",
  "./img/activities/nagamachi-3.jpg",
  "./img/activities/nagamachi.jpg",
  "./img/activities/namba-yasaka-2.jpg",
  "./img/activities/namba-yasaka-3.jpg",
  "./img/activities/namba-yasaka.jpg",
  "./img/activities/nara-park-2.jpg",
  "./img/activities/nara-park-3.jpg",
  "./img/activities/nara-park.jpg",
  "./img/activities/nijo-2.jpg",
  "./img/activities/nijo-3.jpg",
  "./img/activities/nijo.jpg",
  "./img/activities/nishi-chaya-2.jpg",
  "./img/activities/nishi-chaya-3.jpg",
  "./img/activities/nishi-chaya.jpg",
  "./img/activities/nishiki-2.jpg",
  "./img/activities/nishiki-3.jpg",
  "./img/activities/nishiki.jpg",
  "./img/activities/odaiba-2.jpg",
  "./img/activities/odaiba-3.jpg",
  "./img/activities/odaiba.jpg",
  "./img/activities/omicho-2.jpg",
  "./img/activities/omicho-3.jpg",
  "./img/activities/omicho.jpg",
  "./img/activities/osaka-castle-2.jpg",
  "./img/activities/osaka-castle-3.jpg",
  "./img/activities/osaka-castle.jpg",
  "./img/activities/oshino-2.jpg",
  "./img/activities/oshino-3.jpg",
  "./img/activities/oshino.jpg",
  "./img/activities/oyama-2.jpg",
  "./img/activities/oyama-3.jpg",
  "./img/activities/oyama.jpg",
  "./img/activities/philosopher-2.jpg",
  "./img/activities/philosopher-3.jpg",
  "./img/activities/philosopher.jpg",
  "./img/activities/pontocho-2.jpg",
  "./img/activities/pontocho-3.jpg",
  "./img/activities/pontocho.jpg",
  "./img/activities/ropeway-2.jpg",
  "./img/activities/ropeway-3.jpg",
  "./img/activities/ropeway.jpg",
  "./img/activities/saiko-2.jpg",
  "./img/activities/saiko-3.jpg",
  "./img/activities/saiko.jpg",
  "./img/activities/sanmachi-2.jpg",
  "./img/activities/sanmachi.jpg",
  "./img/activities/sensoji-2.jpg",
  "./img/activities/sensoji-3.jpg",
  "./img/activities/sensoji.jpg",
  "./img/activities/shibuya-2.jpg",
  "./img/activities/shibuya-3.jpg",
  "./img/activities/shibuya.jpg",
  "./img/activities/shinjuku-2.jpg",
  "./img/activities/shinjuku-3.jpg",
  "./img/activities/shinjuku.jpg",
  "./img/activities/shinsaibashi-2.jpg",
  "./img/activities/shinsaibashi-3.jpg",
  "./img/activities/shinsaibashi.jpg",
  "./img/activities/shinsekai-2.jpg",
  "./img/activities/shinsekai.jpg",
  "./img/activities/shirakawa-2.jpg",
  "./img/activities/shirakawa-3.jpg",
  "./img/activities/shirakawa.jpg",
  "./img/activities/sumida-2.jpg",
  "./img/activities/sumida-3.jpg",
  "./img/activities/sumida.jpg",
  "./img/activities/tea-2.jpg",
  "./img/activities/tea-3.jpg",
  "./img/activities/tea.jpg",
  "./img/activities/teamlab-2.jpg",
  "./img/activities/teamlab-3.jpg",
  "./img/activities/teamlab.jpg",
  "./img/activities/teramachi.jpg",
  "./img/activities/thumb/akihabara-2.jpg",
  "./img/activities/thumb/akihabara-3.jpg",
  "./img/activities/thumb/akihabara.jpg",
  "./img/activities/thumb/animate.jpg",
  "./img/activities/thumb/arashiyama-2.jpg",
  "./img/activities/thumb/arashiyama-3.jpg",
  "./img/activities/thumb/arashiyama.jpg",
  "./img/activities/thumb/character-street-2.jpg",
  "./img/activities/thumb/character-street-3.jpg",
  "./img/activities/thumb/character-street.jpg",
  "./img/activities/thumb/chureito-2.jpg",
  "./img/activities/thumb/chureito-3.jpg",
  "./img/activities/thumb/chureito.jpg",
  "./img/activities/thumb/daigo-2.jpg",
  "./img/activities/thumb/daigo-3.jpg",
  "./img/activities/thumb/daigo.jpg",
  "./img/activities/thumb/denden-2.jpg",
  "./img/activities/thumb/denden.jpg",
  "./img/activities/thumb/dotonbori-2.jpg",
  "./img/activities/thumb/dotonbori-3.jpg",
  "./img/activities/thumb/dotonbori.jpg",
  "./img/activities/thumb/fujiq-2.jpg",
  "./img/activities/thumb/fujiq-3.jpg",
  "./img/activities/thumb/fujiq.jpg",
  "./img/activities/thumb/fushimi-2.jpg",
  "./img/activities/thumb/fushimi-3.jpg",
  "./img/activities/thumb/fushimi.jpg",
  "./img/activities/thumb/ginza-2.jpg",
  "./img/activities/thumb/ginza-3.jpg",
  "./img/activities/thumb/ginza.jpg",
  "./img/activities/thumb/gold-leaf-2.jpg",
  "./img/activities/thumb/gold-leaf.jpg",
  "./img/activities/thumb/harajuku-2.jpg",
  "./img/activities/thumb/harajuku-3.jpg",
  "./img/activities/thumb/harajuku.jpg",
  "./img/activities/thumb/higashi-chaya-2.jpg",
  "./img/activities/thumb/higashi-chaya-3.jpg",
  "./img/activities/thumb/higashi-chaya.jpg",
  "./img/activities/thumb/hozenji-2.jpg",
  "./img/activities/thumb/hozenji-3.jpg",
  "./img/activities/thumb/hozenji.jpg",
  "./img/activities/thumb/imperial-2.jpg",
  "./img/activities/thumb/imperial-3.jpg",
  "./img/activities/thumb/imperial.jpg",
  "./img/activities/thumb/itchiku-2.jpg",
  "./img/activities/thumb/itchiku-3.jpg",
  "./img/activities/thumb/itchiku.jpg",
  "./img/activities/thumb/jinya-2.jpg",
  "./img/activities/thumb/jinya-3.jpg",
  "./img/activities/thumb/jinya.jpg",
  "./img/activities/thumb/kanazawa-castle-2.jpg",
  "./img/activities/thumb/kanazawa-castle-3.jpg",
  "./img/activities/thumb/kanazawa-castle.jpg",
  "./img/activities/thumb/kanazawa-museum-2.jpg",
  "./img/activities/thumb/kanazawa-museum-3.jpg",
  "./img/activities/thumb/kanazawa-museum.jpg",
  "./img/activities/thumb/kasuga-2.jpg",
  "./img/activities/thumb/kasuga-3.jpg",
  "./img/activities/thumb/kasuga.jpg",
  "./img/activities/thumb/kawaguchi-2.jpg",
  "./img/activities/thumb/kawaguchi-3.jpg",
  "./img/activities/thumb/kawaguchi.jpg",
  "./img/activities/thumb/kenrokuen-2.jpg",
  "./img/activities/thumb/kenrokuen-3.jpg",
  "./img/activities/thumb/kenrokuen.jpg",
  "./img/activities/thumb/kinkakuji-2.jpg",
  "./img/activities/thumb/kinkakuji-3.jpg",
  "./img/activities/thumb/kinkakuji.jpg",
  "./img/activities/thumb/kiyomizu-2.jpg",
  "./img/activities/thumb/kiyomizu-3.jpg",
  "./img/activities/thumb/kiyomizu.jpg",
  "./img/activities/thumb/kofukuji-2.jpg",
  "./img/activities/thumb/kofukuji-3.jpg",
  "./img/activities/thumb/kofukuji.jpg",
  "./img/activities/thumb/kuromon-2.jpg",
  "./img/activities/thumb/kuromon-3.jpg",
  "./img/activities/thumb/kuromon.jpg",
  "./img/activities/thumb/meiji-2.jpg",
  "./img/activities/thumb/meiji-3.jpg",
  "./img/activities/thumb/meiji.jpg",
  "./img/activities/thumb/miyagawa-2.jpg",
  "./img/activities/thumb/miyagawa-3.jpg",
  "./img/activities/thumb/miyagawa.jpg",
  "./img/activities/thumb/momiji.jpg",
  "./img/activities/thumb/music-forest-2.jpg",
  "./img/activities/thumb/music-forest-3.jpg",
  "./img/activities/thumb/music-forest.jpg",
  "./img/activities/thumb/myoryuji.jpg",
  "./img/activities/thumb/nagamachi-2.jpg",
  "./img/activities/thumb/nagamachi-3.jpg",
  "./img/activities/thumb/nagamachi.jpg",
  "./img/activities/thumb/namba-yasaka-2.jpg",
  "./img/activities/thumb/namba-yasaka-3.jpg",
  "./img/activities/thumb/namba-yasaka.jpg",
  "./img/activities/thumb/nara-park-2.jpg",
  "./img/activities/thumb/nara-park-3.jpg",
  "./img/activities/thumb/nara-park.jpg",
  "./img/activities/thumb/nijo-2.jpg",
  "./img/activities/thumb/nijo-3.jpg",
  "./img/activities/thumb/nijo.jpg",
  "./img/activities/thumb/nishi-chaya-2.jpg",
  "./img/activities/thumb/nishi-chaya-3.jpg",
  "./img/activities/thumb/nishi-chaya.jpg",
  "./img/activities/thumb/nishiki-2.jpg",
  "./img/activities/thumb/nishiki-3.jpg",
  "./img/activities/thumb/nishiki.jpg",
  "./img/activities/thumb/odaiba-2.jpg",
  "./img/activities/thumb/odaiba-3.jpg",
  "./img/activities/thumb/odaiba.jpg",
  "./img/activities/thumb/omicho-2.jpg",
  "./img/activities/thumb/omicho-3.jpg",
  "./img/activities/thumb/omicho.jpg",
  "./img/activities/thumb/osaka-castle-2.jpg",
  "./img/activities/thumb/osaka-castle-3.jpg",
  "./img/activities/thumb/osaka-castle.jpg",
  "./img/activities/thumb/oshino-2.jpg",
  "./img/activities/thumb/oshino-3.jpg",
  "./img/activities/thumb/oshino.jpg",
  "./img/activities/thumb/oyama-2.jpg",
  "./img/activities/thumb/oyama-3.jpg",
  "./img/activities/thumb/oyama.jpg",
  "./img/activities/thumb/philosopher-2.jpg",
  "./img/activities/thumb/philosopher-3.jpg",
  "./img/activities/thumb/philosopher.jpg",
  "./img/activities/thumb/pontocho-2.jpg",
  "./img/activities/thumb/pontocho-3.jpg",
  "./img/activities/thumb/pontocho.jpg",
  "./img/activities/thumb/ropeway-2.jpg",
  "./img/activities/thumb/ropeway-3.jpg",
  "./img/activities/thumb/ropeway.jpg",
  "./img/activities/thumb/saiko-2.jpg",
  "./img/activities/thumb/saiko-3.jpg",
  "./img/activities/thumb/saiko.jpg",
  "./img/activities/thumb/sanmachi-2.jpg",
  "./img/activities/thumb/sanmachi.jpg",
  "./img/activities/thumb/sensoji-2.jpg",
  "./img/activities/thumb/sensoji-3.jpg",
  "./img/activities/thumb/sensoji.jpg",
  "./img/activities/thumb/shibuya-2.jpg",
  "./img/activities/thumb/shibuya-3.jpg",
  "./img/activities/thumb/shibuya.jpg",
  "./img/activities/thumb/shinjuku-2.jpg",
  "./img/activities/thumb/shinjuku-3.jpg",
  "./img/activities/thumb/shinjuku.jpg",
  "./img/activities/thumb/shinsaibashi-2.jpg",
  "./img/activities/thumb/shinsaibashi-3.jpg",
  "./img/activities/thumb/shinsaibashi.jpg",
  "./img/activities/thumb/shinsekai-2.jpg",
  "./img/activities/thumb/shinsekai.jpg",
  "./img/activities/thumb/shirakawa-2.jpg",
  "./img/activities/thumb/shirakawa-3.jpg",
  "./img/activities/thumb/shirakawa.jpg",
  "./img/activities/thumb/sumida-2.jpg",
  "./img/activities/thumb/sumida-3.jpg",
  "./img/activities/thumb/sumida.jpg",
  "./img/activities/thumb/tea-2.jpg",
  "./img/activities/thumb/tea-3.jpg",
  "./img/activities/thumb/tea.jpg",
  "./img/activities/thumb/teamlab-2.jpg",
  "./img/activities/thumb/teamlab-3.jpg",
  "./img/activities/thumb/teamlab.jpg",
  "./img/activities/thumb/teramachi.jpg",
  "./img/activities/thumb/todaiji-2.jpg",
  "./img/activities/thumb/todaiji-3.jpg",
  "./img/activities/thumb/todaiji.jpg",
  "./img/activities/thumb/tokyo-tower-2.jpg",
  "./img/activities/thumb/tokyo-tower-3.jpg",
  "./img/activities/thumb/tokyo-tower.jpg",
  "./img/activities/thumb/ueno-2.jpg",
  "./img/activities/thumb/ueno-3.jpg",
  "./img/activities/thumb/ueno.jpg",
  "./img/activities/thumb/usj-2.jpg",
  "./img/activities/thumb/usj-3.jpg",
  "./img/activities/thumb/usj.jpg",
  "./img/activities/thumb/wagashi-2.jpg",
  "./img/activities/thumb/wagashi-3.jpg",
  "./img/activities/thumb/wagashi.jpg",
  "./img/activities/thumb/yanaka-2.jpg",
  "./img/activities/thumb/yanaka-3.jpg",
  "./img/activities/thumb/yanaka.jpg",
  "./img/activities/thumb/yasaka-2.jpg",
  "./img/activities/thumb/yasaka-3.jpg",
  "./img/activities/thumb/yasaka.jpg",
  "./img/activities/todaiji-2.jpg",
  "./img/activities/todaiji-3.jpg",
  "./img/activities/todaiji.jpg",
  "./img/activities/tokyo-tower-2.jpg",
  "./img/activities/tokyo-tower-3.jpg",
  "./img/activities/tokyo-tower.jpg",
  "./img/activities/ueno-2.jpg",
  "./img/activities/ueno-3.jpg",
  "./img/activities/ueno.jpg",
  "./img/activities/usj-2.jpg",
  "./img/activities/usj-3.jpg",
  "./img/activities/usj.jpg",
  "./img/activities/wagashi-2.jpg",
  "./img/activities/wagashi-3.jpg",
  "./img/activities/wagashi.jpg",
  "./img/activities/yanaka-2.jpg",
  "./img/activities/yanaka-3.jpg",
  "./img/activities/yanaka.jpg",
  "./img/activities/yasaka-2.jpg",
  "./img/activities/yasaka-3.jpg",
  "./img/activities/yasaka.jpg",
  "./img/hotels/agora-kyoto-2.jpg",
  "./img/hotels/agora-kyoto-3.jpg",
  "./img/hotels/agora-kyoto-4.jpg",
  "./img/hotels/agora-kyoto.jpg",
  "./img/hotels/deer-park-nara-2.jpg",
  "./img/hotels/deer-park-nara-3.jpg",
  "./img/hotels/deer-park-nara-4.jpg",
  "./img/hotels/deer-park-nara.jpg",
  "./img/hotels/garner-osaka-2.jpg",
  "./img/hotels/garner-osaka-3.jpg",
  "./img/hotels/garner-osaka-4.jpg",
  "./img/hotels/garner-osaka.jpg",
  "./img/hotels/henn-na-kanazawa-2.jpg",
  "./img/hotels/henn-na-kanazawa-3.jpg",
  "./img/hotels/henn-na-kanazawa-4.jpg",
  "./img/hotels/henn-na-kanazawa.jpg",
  "./img/hotels/homenest-akihabara-2.jpg",
  "./img/hotels/homenest-akihabara-3.jpg",
  "./img/hotels/homenest-akihabara-4.jpg",
  "./img/hotels/homenest-akihabara-5.jpg",
  "./img/hotels/homenest-akihabara-6.jpg",
  "./img/hotels/homenest-akihabara.jpg",
  "./img/hotels/kawaguchiko-2.jpg",
  "./img/hotels/kawaguchiko-3.jpg",
  "./img/hotels/kawaguchiko-4.jpg",
  "./img/hotels/kawaguchiko.jpg",
  "./img/hotels/mercure-takayama-2.jpg",
  "./img/hotels/mercure-takayama-3.jpg",
  "./img/hotels/mercure-takayama-4.jpg",
  "./img/hotels/mercure-takayama.jpg",
  "./img/hotels/royal-park-haneda-2.jpg",
  "./img/hotels/royal-park-haneda-3.jpg",
  "./img/hotels/royal-park-haneda-4.jpg",
  "./img/hotels/royal-park-haneda.jpg",
  "./img/hotels/thumb/agora-kyoto-2.jpg",
  "./img/hotels/thumb/agora-kyoto-3.jpg",
  "./img/hotels/thumb/agora-kyoto-4.jpg",
  "./img/hotels/thumb/agora-kyoto.jpg",
  "./img/hotels/thumb/deer-park-nara-2.jpg",
  "./img/hotels/thumb/deer-park-nara-3.jpg",
  "./img/hotels/thumb/deer-park-nara-4.jpg",
  "./img/hotels/thumb/deer-park-nara.jpg",
  "./img/hotels/thumb/garner-osaka-2.jpg",
  "./img/hotels/thumb/garner-osaka-3.jpg",
  "./img/hotels/thumb/garner-osaka-4.jpg",
  "./img/hotels/thumb/garner-osaka.jpg",
  "./img/hotels/thumb/henn-na-kanazawa-2.jpg",
  "./img/hotels/thumb/henn-na-kanazawa-3.jpg",
  "./img/hotels/thumb/henn-na-kanazawa-4.jpg",
  "./img/hotels/thumb/henn-na-kanazawa.jpg",
  "./img/hotels/thumb/homenest-akihabara-2.jpg",
  "./img/hotels/thumb/homenest-akihabara-3.jpg",
  "./img/hotels/thumb/homenest-akihabara-4.jpg",
  "./img/hotels/thumb/homenest-akihabara-5.jpg",
  "./img/hotels/thumb/homenest-akihabara-6.jpg",
  "./img/hotels/thumb/homenest-akihabara.jpg",
  "./img/hotels/thumb/kawaguchiko-2.jpg",
  "./img/hotels/thumb/kawaguchiko-3.jpg",
  "./img/hotels/thumb/kawaguchiko-4.jpg",
  "./img/hotels/thumb/kawaguchiko.jpg",
  "./img/hotels/thumb/mercure-takayama-2.jpg",
  "./img/hotels/thumb/mercure-takayama-3.jpg",
  "./img/hotels/thumb/mercure-takayama-4.jpg",
  "./img/hotels/thumb/mercure-takayama.jpg",
  "./img/hotels/thumb/royal-park-haneda-2.jpg",
  "./img/hotels/thumb/royal-park-haneda-3.jpg",
  "./img/hotels/thumb/royal-park-haneda-4.jpg",
  "./img/hotels/thumb/royal-park-haneda.jpg",
  "./img/icon-180.png",
  "./img/icon-192.png",
  "./img/icon-512.png",
  "./img/logo.svg",
  "./lib/maplibre/maplibre-gl.css",
  "./lib/maplibre/maplibre-gl.js",
  "./src/config.js",
  "./src/core/checklist-store.js",
  "./src/core/data.js",
  "./src/core/dates.js",
  "./src/core/dom.js",
  "./src/core/elements.js",
  "./src/core/env.js",
  "./src/core/hooks.js",
  "./src/core/state.js",
  "./src/domain/bookings.js",
  "./src/domain/classify.js",
  "./src/domain/itinerary.js",
  "./src/domain/legs.js",
  "./src/domain/photos.js",
  "./src/domain/places.js",
  "./src/domain/trip.js",
  "./src/main.js",
  "./src/map/city.js",
  "./src/map/controller.js",
  "./src/map/country.js",
  "./src/map/day-route.js",
  "./src/map/geo.js",
  "./src/map/map-style.js",
  "./src/map/map-view.js",
  "./src/map/offline-tiles.js",
  "./src/map/routes.js",
  "./src/pwa/sw-register.js",
  "./src/shared/icons.js",
  "./src/ui/alerts.js",
  "./src/ui/app-shell.js",
  "./src/ui/city-list.js",
  "./src/ui/map-controls.js",
  "./src/ui/panels/city-panel.js",
  "./src/ui/panels/leg-panel.js",
  "./src/ui/panels/panel.js",
  "./src/ui/panels/sheet.js",
  "./src/ui/phrase-show.js",
  "./src/ui/tabs.js",
  "./src/ui/templates.js",
  "./src/ui/theme.js",
  "./src/ui/views/fx-converter.js",
  "./src/ui/views/onsite-view.js",
  "./src/ui/views/prep-view.js",
  "./src/ui/views/print.js",
  "./src/ui/views/settings-view.js",
  "./src/ui/views/weather.js",
  "./styles/base.css",
  "./styles/components.css",
  "./styles/map.css",
  "./styles/mobile.css",
  "./styles/panel.css",
  "./styles/print.css",
  "./styles/settings.css",
  "./styles/standalone.css",
  "./styles/theme-light.css",
  "./styles/tokens.css",
  "./styles/views.css"
];
const IMG_HASH = {
  "./img/activities/akihabara-2.jpg": "7dce22f718",
  "./img/activities/akihabara-3.jpg": "e50c142da1",
  "./img/activities/akihabara.jpg": "95a3673eb0",
  "./img/activities/animate.jpg": "60e0656b00",
  "./img/activities/arashiyama-2.jpg": "d8ef3623d1",
  "./img/activities/arashiyama-3.jpg": "8d7806978b",
  "./img/activities/arashiyama.jpg": "611c1974a4",
  "./img/activities/character-street-2.jpg": "1b87a9b800",
  "./img/activities/character-street-3.jpg": "2c6cb8daa3",
  "./img/activities/character-street.jpg": "ceaca6758e",
  "./img/activities/chureito-2.jpg": "2e0fc9722a",
  "./img/activities/chureito-3.jpg": "88593a7c30",
  "./img/activities/chureito.jpg": "7ce9c4f820",
  "./img/activities/daigo-2.jpg": "35243264fb",
  "./img/activities/daigo-3.jpg": "b5ccdbbfd3",
  "./img/activities/daigo.jpg": "2ef368e7ca",
  "./img/activities/denden-2.jpg": "cfc6cc4349",
  "./img/activities/denden.jpg": "a8a183f373",
  "./img/activities/dotonbori-2.jpg": "f172aae559",
  "./img/activities/dotonbori-3.jpg": "05e84f026b",
  "./img/activities/dotonbori.jpg": "105f711d33",
  "./img/activities/fujiq-2.jpg": "c36006ec70",
  "./img/activities/fujiq-3.jpg": "efae8e0c49",
  "./img/activities/fujiq.jpg": "7395d242b7",
  "./img/activities/fushimi-2.jpg": "6ce8f1d473",
  "./img/activities/fushimi-3.jpg": "3612fc997e",
  "./img/activities/fushimi.jpg": "c5e875c75a",
  "./img/activities/ginza-2.jpg": "056b7d7c1b",
  "./img/activities/ginza-3.jpg": "626690969a",
  "./img/activities/ginza.jpg": "a845429e66",
  "./img/activities/gold-leaf-2.jpg": "dd31cf1813",
  "./img/activities/gold-leaf.jpg": "641ac608bf",
  "./img/activities/harajuku-2.jpg": "272a2d82de",
  "./img/activities/harajuku-3.jpg": "b67a1c54dc",
  "./img/activities/harajuku.jpg": "4ce8644f4f",
  "./img/activities/higashi-chaya-2.jpg": "13cfc3bf38",
  "./img/activities/higashi-chaya-3.jpg": "d12e40ac44",
  "./img/activities/higashi-chaya.jpg": "104e1a986f",
  "./img/activities/hozenji-2.jpg": "5a38c56b29",
  "./img/activities/hozenji-3.jpg": "53097f6609",
  "./img/activities/hozenji.jpg": "aaa0b742a0",
  "./img/activities/imperial-2.jpg": "30f443a570",
  "./img/activities/imperial-3.jpg": "c1ba3b99c7",
  "./img/activities/imperial.jpg": "11e4c6db04",
  "./img/activities/itchiku-2.jpg": "2f3bb89b66",
  "./img/activities/itchiku-3.jpg": "a3c88b0ad6",
  "./img/activities/itchiku.jpg": "22843f149a",
  "./img/activities/jinya-2.jpg": "c51fef73e5",
  "./img/activities/jinya-3.jpg": "1577c11806",
  "./img/activities/jinya.jpg": "8ac92dc878",
  "./img/activities/kanazawa-castle-2.jpg": "92c032c9e7",
  "./img/activities/kanazawa-castle-3.jpg": "ac12ad3e42",
  "./img/activities/kanazawa-castle.jpg": "93eb61f7c0",
  "./img/activities/kanazawa-museum-2.jpg": "58f94f0c1a",
  "./img/activities/kanazawa-museum-3.jpg": "6d1393ced9",
  "./img/activities/kanazawa-museum.jpg": "152785e60a",
  "./img/activities/kasuga-2.jpg": "d01e544963",
  "./img/activities/kasuga-3.jpg": "9248664894",
  "./img/activities/kasuga.jpg": "ccccf68917",
  "./img/activities/kawaguchi-2.jpg": "0b39b74c92",
  "./img/activities/kawaguchi-3.jpg": "879fe2cfd8",
  "./img/activities/kawaguchi.jpg": "5a1ecb1887",
  "./img/activities/kenrokuen-2.jpg": "0660f45d24",
  "./img/activities/kenrokuen-3.jpg": "77f90363de",
  "./img/activities/kenrokuen.jpg": "7de0ae834d",
  "./img/activities/kinkakuji-2.jpg": "d4f1f709a7",
  "./img/activities/kinkakuji-3.jpg": "365cbc4170",
  "./img/activities/kinkakuji.jpg": "1de006bcbf",
  "./img/activities/kiyomizu-2.jpg": "20d9ec016b",
  "./img/activities/kiyomizu-3.jpg": "983046ff9d",
  "./img/activities/kiyomizu.jpg": "426cf6069b",
  "./img/activities/kofukuji-2.jpg": "9fe5403e4b",
  "./img/activities/kofukuji-3.jpg": "eaebd82dac",
  "./img/activities/kofukuji.jpg": "0dc692a5e5",
  "./img/activities/kuromon-2.jpg": "ec8d129132",
  "./img/activities/kuromon-3.jpg": "24791b5a6e",
  "./img/activities/kuromon.jpg": "9c10a6646a",
  "./img/activities/meiji-2.jpg": "7f5a83ecc5",
  "./img/activities/meiji-3.jpg": "21ce7145e4",
  "./img/activities/meiji.jpg": "c7677d49de",
  "./img/activities/miyagawa-2.jpg": "fba77cfa24",
  "./img/activities/miyagawa-3.jpg": "1ae035434f",
  "./img/activities/miyagawa.jpg": "9a7568169e",
  "./img/activities/momiji.jpg": "1da6f27785",
  "./img/activities/music-forest-2.jpg": "8f6767402a",
  "./img/activities/music-forest-3.jpg": "0f1572de23",
  "./img/activities/music-forest.jpg": "f18f6560cf",
  "./img/activities/myoryuji.jpg": "f4ed6ead81",
  "./img/activities/nagamachi-2.jpg": "96e1b0f830",
  "./img/activities/nagamachi-3.jpg": "147f6f2a01",
  "./img/activities/nagamachi.jpg": "20a711d5d4",
  "./img/activities/namba-yasaka-2.jpg": "2f067525e5",
  "./img/activities/namba-yasaka-3.jpg": "39b4848127",
  "./img/activities/namba-yasaka.jpg": "d610749dff",
  "./img/activities/nara-park-2.jpg": "946e6a9d46",
  "./img/activities/nara-park-3.jpg": "3995d4b992",
  "./img/activities/nara-park.jpg": "6b3a85e56b",
  "./img/activities/nijo-2.jpg": "c24513ae3c",
  "./img/activities/nijo-3.jpg": "0f0ae5f3a9",
  "./img/activities/nijo.jpg": "9ab83c5b38",
  "./img/activities/nishi-chaya-2.jpg": "16c29ca397",
  "./img/activities/nishi-chaya-3.jpg": "8664f504f7",
  "./img/activities/nishi-chaya.jpg": "0f120c8f6c",
  "./img/activities/nishiki-2.jpg": "729cf9326b",
  "./img/activities/nishiki-3.jpg": "1b0f31f6ae",
  "./img/activities/nishiki.jpg": "0c71c3f20c",
  "./img/activities/odaiba-2.jpg": "663de3cfcf",
  "./img/activities/odaiba-3.jpg": "a657aea732",
  "./img/activities/odaiba.jpg": "ea766def30",
  "./img/activities/omicho-2.jpg": "5c5a34740c",
  "./img/activities/omicho-3.jpg": "281762abcf",
  "./img/activities/omicho.jpg": "f4bb891cdb",
  "./img/activities/osaka-castle-2.jpg": "de986da823",
  "./img/activities/osaka-castle-3.jpg": "b8c4835a25",
  "./img/activities/osaka-castle.jpg": "251c782ebd",
  "./img/activities/oshino-2.jpg": "c5d568beaa",
  "./img/activities/oshino-3.jpg": "a92df95170",
  "./img/activities/oshino.jpg": "c52ca0a32c",
  "./img/activities/oyama-2.jpg": "4bb23b7a0d",
  "./img/activities/oyama-3.jpg": "ab7e71c13a",
  "./img/activities/oyama.jpg": "00e0802b48",
  "./img/activities/philosopher-2.jpg": "3173d91aaa",
  "./img/activities/philosopher-3.jpg": "54debc2ba4",
  "./img/activities/philosopher.jpg": "34b022c105",
  "./img/activities/pontocho-2.jpg": "7e9e04254a",
  "./img/activities/pontocho-3.jpg": "9d9ff75813",
  "./img/activities/pontocho.jpg": "4a71e590d2",
  "./img/activities/ropeway-2.jpg": "cf2bd730dd",
  "./img/activities/ropeway-3.jpg": "672a1c9291",
  "./img/activities/ropeway.jpg": "6e617ecc9e",
  "./img/activities/saiko-2.jpg": "d2ae162d82",
  "./img/activities/saiko-3.jpg": "ccaf9e9c34",
  "./img/activities/saiko.jpg": "2b88bae39d",
  "./img/activities/sanmachi-2.jpg": "3a53aafff7",
  "./img/activities/sanmachi.jpg": "e4c64892b7",
  "./img/activities/sensoji-2.jpg": "1237be7387",
  "./img/activities/sensoji-3.jpg": "5f557c7361",
  "./img/activities/sensoji.jpg": "ea391b3dee",
  "./img/activities/shibuya-2.jpg": "c7c8cd7547",
  "./img/activities/shibuya-3.jpg": "29af6d092c",
  "./img/activities/shibuya.jpg": "f2b21aa987",
  "./img/activities/shinjuku-2.jpg": "8333fe0f31",
  "./img/activities/shinjuku-3.jpg": "d346d49e44",
  "./img/activities/shinjuku.jpg": "668cf142a9",
  "./img/activities/shinsaibashi-2.jpg": "74391ec91c",
  "./img/activities/shinsaibashi-3.jpg": "e0c3c16d38",
  "./img/activities/shinsaibashi.jpg": "4ddaa6fa97",
  "./img/activities/shinsekai-2.jpg": "9a52f1cc7c",
  "./img/activities/shinsekai.jpg": "163baa2492",
  "./img/activities/shirakawa-2.jpg": "198bb55e33",
  "./img/activities/shirakawa-3.jpg": "a9b2f17caf",
  "./img/activities/shirakawa.jpg": "b5dd4df974",
  "./img/activities/sumida-2.jpg": "d4079599dc",
  "./img/activities/sumida-3.jpg": "4d278fb996",
  "./img/activities/sumida.jpg": "2805aa703f",
  "./img/activities/tea-2.jpg": "8cf32f4055",
  "./img/activities/tea-3.jpg": "3b92d218fa",
  "./img/activities/tea.jpg": "8c55dbf5b1",
  "./img/activities/teamlab-2.jpg": "50fdc7f63b",
  "./img/activities/teamlab-3.jpg": "507943b597",
  "./img/activities/teamlab.jpg": "d71e55fb36",
  "./img/activities/teramachi.jpg": "ad57cf0f0d",
  "./img/activities/thumb/akihabara-2.jpg": "425e2c54c6",
  "./img/activities/thumb/akihabara-3.jpg": "f1b7c74a21",
  "./img/activities/thumb/akihabara.jpg": "27afc52513",
  "./img/activities/thumb/animate.jpg": "002e88f4e1",
  "./img/activities/thumb/arashiyama-2.jpg": "00b2ecd271",
  "./img/activities/thumb/arashiyama-3.jpg": "3dd8578d60",
  "./img/activities/thumb/arashiyama.jpg": "3026a17dfc",
  "./img/activities/thumb/character-street-2.jpg": "c96eb5f99a",
  "./img/activities/thumb/character-street-3.jpg": "050585d478",
  "./img/activities/thumb/character-street.jpg": "922eb77ca0",
  "./img/activities/thumb/chureito-2.jpg": "eba5c9a72a",
  "./img/activities/thumb/chureito-3.jpg": "bfd09a298e",
  "./img/activities/thumb/chureito.jpg": "1c6fc0bf0a",
  "./img/activities/thumb/daigo-2.jpg": "f4acc3884e",
  "./img/activities/thumb/daigo-3.jpg": "9143b5951e",
  "./img/activities/thumb/daigo.jpg": "8ec4484d2e",
  "./img/activities/thumb/denden-2.jpg": "919c016595",
  "./img/activities/thumb/denden.jpg": "1067ad8035",
  "./img/activities/thumb/dotonbori-2.jpg": "68b3403855",
  "./img/activities/thumb/dotonbori-3.jpg": "be3f75da5a",
  "./img/activities/thumb/dotonbori.jpg": "3379be1071",
  "./img/activities/thumb/fujiq-2.jpg": "2527d9147a",
  "./img/activities/thumb/fujiq-3.jpg": "dd98ea04a4",
  "./img/activities/thumb/fujiq.jpg": "c55dccb222",
  "./img/activities/thumb/fushimi-2.jpg": "6c21e1316b",
  "./img/activities/thumb/fushimi-3.jpg": "6c3e71a60f",
  "./img/activities/thumb/fushimi.jpg": "f72e90ce94",
  "./img/activities/thumb/ginza-2.jpg": "a3e452ae6a",
  "./img/activities/thumb/ginza-3.jpg": "1f9b25f8c0",
  "./img/activities/thumb/ginza.jpg": "da696df39d",
  "./img/activities/thumb/gold-leaf-2.jpg": "ed4838aba4",
  "./img/activities/thumb/gold-leaf.jpg": "4e3a079f24",
  "./img/activities/thumb/harajuku-2.jpg": "19eebf0c89",
  "./img/activities/thumb/harajuku-3.jpg": "70f41447b4",
  "./img/activities/thumb/harajuku.jpg": "c6114705b1",
  "./img/activities/thumb/higashi-chaya-2.jpg": "9451104a47",
  "./img/activities/thumb/higashi-chaya-3.jpg": "3316b5d4cb",
  "./img/activities/thumb/higashi-chaya.jpg": "b55ca5b098",
  "./img/activities/thumb/hozenji-2.jpg": "43e6dff518",
  "./img/activities/thumb/hozenji-3.jpg": "36fc565bbf",
  "./img/activities/thumb/hozenji.jpg": "7772f19a10",
  "./img/activities/thumb/imperial-2.jpg": "c9ac439bbf",
  "./img/activities/thumb/imperial-3.jpg": "db6cde3a91",
  "./img/activities/thumb/imperial.jpg": "4af33d73ac",
  "./img/activities/thumb/itchiku-2.jpg": "4691367ced",
  "./img/activities/thumb/itchiku-3.jpg": "3d6b7ba712",
  "./img/activities/thumb/itchiku.jpg": "7ed2ce5c26",
  "./img/activities/thumb/jinya-2.jpg": "1726ec98e6",
  "./img/activities/thumb/jinya-3.jpg": "b48bfac63f",
  "./img/activities/thumb/jinya.jpg": "79548fffe5",
  "./img/activities/thumb/kanazawa-castle-2.jpg": "dbc43039c6",
  "./img/activities/thumb/kanazawa-castle-3.jpg": "62e0d97dcd",
  "./img/activities/thumb/kanazawa-castle.jpg": "d9a1701b1c",
  "./img/activities/thumb/kanazawa-museum-2.jpg": "3f9433acc0",
  "./img/activities/thumb/kanazawa-museum-3.jpg": "cea4e7d8ff",
  "./img/activities/thumb/kanazawa-museum.jpg": "d2d8f6fa67",
  "./img/activities/thumb/kasuga-2.jpg": "7640abd2c5",
  "./img/activities/thumb/kasuga-3.jpg": "ecbe1e46ed",
  "./img/activities/thumb/kasuga.jpg": "24ce8bda9d",
  "./img/activities/thumb/kawaguchi-2.jpg": "61ad9f9424",
  "./img/activities/thumb/kawaguchi-3.jpg": "eb849a1b32",
  "./img/activities/thumb/kawaguchi.jpg": "13e7c0c1a7",
  "./img/activities/thumb/kenrokuen-2.jpg": "a2b7348027",
  "./img/activities/thumb/kenrokuen-3.jpg": "4052899561",
  "./img/activities/thumb/kenrokuen.jpg": "3f29df83f9",
  "./img/activities/thumb/kinkakuji-2.jpg": "50e92ba175",
  "./img/activities/thumb/kinkakuji-3.jpg": "ca6fafcc9f",
  "./img/activities/thumb/kinkakuji.jpg": "94ab82decd",
  "./img/activities/thumb/kiyomizu-2.jpg": "7c090d58d1",
  "./img/activities/thumb/kiyomizu-3.jpg": "7d10bcb0fa",
  "./img/activities/thumb/kiyomizu.jpg": "4fcbf84dbe",
  "./img/activities/thumb/kofukuji-2.jpg": "15f5cf7832",
  "./img/activities/thumb/kofukuji-3.jpg": "c277d685f9",
  "./img/activities/thumb/kofukuji.jpg": "f69a6b4a5c",
  "./img/activities/thumb/kuromon-2.jpg": "557dbc241c",
  "./img/activities/thumb/kuromon-3.jpg": "82a403cd79",
  "./img/activities/thumb/kuromon.jpg": "e8ff2174a9",
  "./img/activities/thumb/meiji-2.jpg": "c8abe50597",
  "./img/activities/thumb/meiji-3.jpg": "b4587ec128",
  "./img/activities/thumb/meiji.jpg": "77c5f07f4a",
  "./img/activities/thumb/miyagawa-2.jpg": "831071bd4b",
  "./img/activities/thumb/miyagawa-3.jpg": "ef97b36061",
  "./img/activities/thumb/miyagawa.jpg": "43fb284903",
  "./img/activities/thumb/momiji.jpg": "acdc34d004",
  "./img/activities/thumb/music-forest-2.jpg": "efff2981c4",
  "./img/activities/thumb/music-forest-3.jpg": "3feba10cac",
  "./img/activities/thumb/music-forest.jpg": "ddc8c46872",
  "./img/activities/thumb/myoryuji.jpg": "a5d93a161b",
  "./img/activities/thumb/nagamachi-2.jpg": "ba59b32b46",
  "./img/activities/thumb/nagamachi-3.jpg": "9922d6a5c7",
  "./img/activities/thumb/nagamachi.jpg": "ca0ac7c2f3",
  "./img/activities/thumb/namba-yasaka-2.jpg": "6af703e4b0",
  "./img/activities/thumb/namba-yasaka-3.jpg": "01427e6430",
  "./img/activities/thumb/namba-yasaka.jpg": "a3f967c640",
  "./img/activities/thumb/nara-park-2.jpg": "6cf0bfeb9a",
  "./img/activities/thumb/nara-park-3.jpg": "70adccae01",
  "./img/activities/thumb/nara-park.jpg": "f3c423fa2d",
  "./img/activities/thumb/nijo-2.jpg": "c6b6d9cc7a",
  "./img/activities/thumb/nijo-3.jpg": "f950363a4a",
  "./img/activities/thumb/nijo.jpg": "3aec5b62fa",
  "./img/activities/thumb/nishi-chaya-2.jpg": "8d8842d661",
  "./img/activities/thumb/nishi-chaya-3.jpg": "e43c10fe3d",
  "./img/activities/thumb/nishi-chaya.jpg": "842d27b601",
  "./img/activities/thumb/nishiki-2.jpg": "55de61c024",
  "./img/activities/thumb/nishiki-3.jpg": "7004ad13ad",
  "./img/activities/thumb/nishiki.jpg": "a56c97ce8b",
  "./img/activities/thumb/odaiba-2.jpg": "4cad4f29de",
  "./img/activities/thumb/odaiba-3.jpg": "e216f528ad",
  "./img/activities/thumb/odaiba.jpg": "d5a144a10c",
  "./img/activities/thumb/omicho-2.jpg": "f9ea87191b",
  "./img/activities/thumb/omicho-3.jpg": "d139280a2c",
  "./img/activities/thumb/omicho.jpg": "f524454199",
  "./img/activities/thumb/osaka-castle-2.jpg": "64c7e9236b",
  "./img/activities/thumb/osaka-castle-3.jpg": "3e950c6527",
  "./img/activities/thumb/osaka-castle.jpg": "b1465ef48b",
  "./img/activities/thumb/oshino-2.jpg": "6e790a68e6",
  "./img/activities/thumb/oshino-3.jpg": "5031f9aab3",
  "./img/activities/thumb/oshino.jpg": "79ff465694",
  "./img/activities/thumb/oyama-2.jpg": "6aa105b5aa",
  "./img/activities/thumb/oyama-3.jpg": "5513b0eda0",
  "./img/activities/thumb/oyama.jpg": "4f7de0854a",
  "./img/activities/thumb/philosopher-2.jpg": "40794aebaa",
  "./img/activities/thumb/philosopher-3.jpg": "066e2e4de4",
  "./img/activities/thumb/philosopher.jpg": "cd4ecec693",
  "./img/activities/thumb/pontocho-2.jpg": "e1582da76d",
  "./img/activities/thumb/pontocho-3.jpg": "b4e1f052e2",
  "./img/activities/thumb/pontocho.jpg": "a2bbc00b4b",
  "./img/activities/thumb/ropeway-2.jpg": "6643d551f7",
  "./img/activities/thumb/ropeway-3.jpg": "4a703a2663",
  "./img/activities/thumb/ropeway.jpg": "5870d11fe0",
  "./img/activities/thumb/saiko-2.jpg": "23f3219fd4",
  "./img/activities/thumb/saiko-3.jpg": "1619be05bb",
  "./img/activities/thumb/saiko.jpg": "601580ca94",
  "./img/activities/thumb/sanmachi-2.jpg": "69c6735425",
  "./img/activities/thumb/sanmachi.jpg": "cdfe814496",
  "./img/activities/thumb/sensoji-2.jpg": "8c61776d7e",
  "./img/activities/thumb/sensoji-3.jpg": "22c4c91081",
  "./img/activities/thumb/sensoji.jpg": "ca690b33d3",
  "./img/activities/thumb/shibuya-2.jpg": "079ba1400c",
  "./img/activities/thumb/shibuya-3.jpg": "ef7ce19330",
  "./img/activities/thumb/shibuya.jpg": "c411560f37",
  "./img/activities/thumb/shinjuku-2.jpg": "b4255df57d",
  "./img/activities/thumb/shinjuku-3.jpg": "9496abd357",
  "./img/activities/thumb/shinjuku.jpg": "0f76496beb",
  "./img/activities/thumb/shinsaibashi-2.jpg": "54c63e4d8e",
  "./img/activities/thumb/shinsaibashi-3.jpg": "d424f207d8",
  "./img/activities/thumb/shinsaibashi.jpg": "7a70fd7147",
  "./img/activities/thumb/shinsekai-2.jpg": "4c5234681a",
  "./img/activities/thumb/shinsekai.jpg": "f1676a82ac",
  "./img/activities/thumb/shirakawa-2.jpg": "d1511b2491",
  "./img/activities/thumb/shirakawa-3.jpg": "646ce4073c",
  "./img/activities/thumb/shirakawa.jpg": "d4edb446f2",
  "./img/activities/thumb/sumida-2.jpg": "1954592cb1",
  "./img/activities/thumb/sumida-3.jpg": "1b031e20cc",
  "./img/activities/thumb/sumida.jpg": "cd5b9aa8da",
  "./img/activities/thumb/tea-2.jpg": "624fe492a7",
  "./img/activities/thumb/tea-3.jpg": "e7f06e34b3",
  "./img/activities/thumb/tea.jpg": "24c18297e2",
  "./img/activities/thumb/teamlab-2.jpg": "53c04df0f7",
  "./img/activities/thumb/teamlab-3.jpg": "d746264a56",
  "./img/activities/thumb/teamlab.jpg": "04d93d95e5",
  "./img/activities/thumb/teramachi.jpg": "30d9d52150",
  "./img/activities/thumb/todaiji-2.jpg": "1ea7ba7511",
  "./img/activities/thumb/todaiji-3.jpg": "5188e7a434",
  "./img/activities/thumb/todaiji.jpg": "6620bfbc3d",
  "./img/activities/thumb/tokyo-tower-2.jpg": "086a9cd1c9",
  "./img/activities/thumb/tokyo-tower-3.jpg": "a7ef81493a",
  "./img/activities/thumb/tokyo-tower.jpg": "6ab99629d2",
  "./img/activities/thumb/ueno-2.jpg": "e2d6b34761",
  "./img/activities/thumb/ueno-3.jpg": "b944368300",
  "./img/activities/thumb/ueno.jpg": "6b52f31578",
  "./img/activities/thumb/usj-2.jpg": "e900c11254",
  "./img/activities/thumb/usj-3.jpg": "ef18a6e3f2",
  "./img/activities/thumb/usj.jpg": "5df6d0eb58",
  "./img/activities/thumb/wagashi-2.jpg": "3c55e01b00",
  "./img/activities/thumb/wagashi-3.jpg": "78c004c3d6",
  "./img/activities/thumb/wagashi.jpg": "1359a872b2",
  "./img/activities/thumb/yanaka-2.jpg": "1918fc7069",
  "./img/activities/thumb/yanaka-3.jpg": "6db76a2882",
  "./img/activities/thumb/yanaka.jpg": "0d5ef7f52c",
  "./img/activities/thumb/yasaka-2.jpg": "7a2d1aaec8",
  "./img/activities/thumb/yasaka-3.jpg": "e4688a28ce",
  "./img/activities/thumb/yasaka.jpg": "afca975a64",
  "./img/activities/todaiji-2.jpg": "37ba80bbba",
  "./img/activities/todaiji-3.jpg": "e2f2a4adb4",
  "./img/activities/todaiji.jpg": "2d650410fe",
  "./img/activities/tokyo-tower-2.jpg": "e735fa33c2",
  "./img/activities/tokyo-tower-3.jpg": "23753ce48a",
  "./img/activities/tokyo-tower.jpg": "4455bedaf4",
  "./img/activities/ueno-2.jpg": "284697b030",
  "./img/activities/ueno-3.jpg": "4d356c2c18",
  "./img/activities/ueno.jpg": "ad812e7ba2",
  "./img/activities/usj-2.jpg": "637403deb6",
  "./img/activities/usj-3.jpg": "c4207ac7a8",
  "./img/activities/usj.jpg": "c6f7a5cc39",
  "./img/activities/wagashi-2.jpg": "2e34df0b2a",
  "./img/activities/wagashi-3.jpg": "9fa8ff9032",
  "./img/activities/wagashi.jpg": "1404a6bdfd",
  "./img/activities/yanaka-2.jpg": "0a96f79d2b",
  "./img/activities/yanaka-3.jpg": "b06d7cb79b",
  "./img/activities/yanaka.jpg": "36be0d94a9",
  "./img/activities/yasaka-2.jpg": "e8c7d81a13",
  "./img/activities/yasaka-3.jpg": "b872e5ca7c",
  "./img/activities/yasaka.jpg": "cef9c2adbe",
  "./img/hotels/agora-kyoto-2.jpg": "8ef1f0b7c2",
  "./img/hotels/agora-kyoto-3.jpg": "ad1bcd2257",
  "./img/hotels/agora-kyoto-4.jpg": "babca7fd51",
  "./img/hotels/agora-kyoto.jpg": "f9b9a5e7da",
  "./img/hotels/deer-park-nara-2.jpg": "36a563f217",
  "./img/hotels/deer-park-nara-3.jpg": "0a7aac4265",
  "./img/hotels/deer-park-nara-4.jpg": "89fcb5c137",
  "./img/hotels/deer-park-nara.jpg": "6c09a49308",
  "./img/hotels/garner-osaka-2.jpg": "39e4ffe592",
  "./img/hotels/garner-osaka-3.jpg": "ef133e66db",
  "./img/hotels/garner-osaka-4.jpg": "30c1bb1ab4",
  "./img/hotels/garner-osaka.jpg": "3d723cfdd3",
  "./img/hotels/henn-na-kanazawa-2.jpg": "c035ca46b1",
  "./img/hotels/henn-na-kanazawa-3.jpg": "8f5088dea4",
  "./img/hotels/henn-na-kanazawa-4.jpg": "8342e8d6aa",
  "./img/hotels/henn-na-kanazawa.jpg": "9676d877ab",
  "./img/hotels/homenest-akihabara-2.jpg": "106e6d0cad",
  "./img/hotels/homenest-akihabara-3.jpg": "ddf9985175",
  "./img/hotels/homenest-akihabara-4.jpg": "9baf2e41c3",
  "./img/hotels/homenest-akihabara-5.jpg": "2bcb4a02cf",
  "./img/hotels/homenest-akihabara-6.jpg": "3d17c4eb8c",
  "./img/hotels/homenest-akihabara.jpg": "ff1b493b8b",
  "./img/hotels/kawaguchiko-2.jpg": "9db3069b26",
  "./img/hotels/kawaguchiko-3.jpg": "9735e35928",
  "./img/hotels/kawaguchiko-4.jpg": "0e5e325dd4",
  "./img/hotels/kawaguchiko.jpg": "d7fdcb6083",
  "./img/hotels/mercure-takayama-2.jpg": "2cf6be61f1",
  "./img/hotels/mercure-takayama-3.jpg": "00ee7ca41f",
  "./img/hotels/mercure-takayama-4.jpg": "9a810d119b",
  "./img/hotels/mercure-takayama.jpg": "96850c77f1",
  "./img/hotels/royal-park-haneda-2.jpg": "2e73c91783",
  "./img/hotels/royal-park-haneda-3.jpg": "3fe7bba663",
  "./img/hotels/royal-park-haneda-4.jpg": "f38a03945f",
  "./img/hotels/royal-park-haneda.jpg": "7d72d23dac",
  "./img/hotels/thumb/agora-kyoto-2.jpg": "88a6fa86f2",
  "./img/hotels/thumb/agora-kyoto-3.jpg": "43bfbbb5af",
  "./img/hotels/thumb/agora-kyoto-4.jpg": "ee0f191d3f",
  "./img/hotels/thumb/agora-kyoto.jpg": "d27a83e11f",
  "./img/hotels/thumb/deer-park-nara-2.jpg": "a4453b4c8b",
  "./img/hotels/thumb/deer-park-nara-3.jpg": "ea6efab24f",
  "./img/hotels/thumb/deer-park-nara-4.jpg": "e23c09cee7",
  "./img/hotels/thumb/deer-park-nara.jpg": "4d44828a83",
  "./img/hotels/thumb/garner-osaka-2.jpg": "f7bb953403",
  "./img/hotels/thumb/garner-osaka-3.jpg": "e5e748cb4b",
  "./img/hotels/thumb/garner-osaka-4.jpg": "15ac663ba4",
  "./img/hotels/thumb/garner-osaka.jpg": "121f8b3d7d",
  "./img/hotels/thumb/henn-na-kanazawa-2.jpg": "eb9a20a3ef",
  "./img/hotels/thumb/henn-na-kanazawa-3.jpg": "245f0c775a",
  "./img/hotels/thumb/henn-na-kanazawa-4.jpg": "8778016ea4",
  "./img/hotels/thumb/henn-na-kanazawa.jpg": "7302f95b8e",
  "./img/hotels/thumb/homenest-akihabara-2.jpg": "f8700d37ed",
  "./img/hotels/thumb/homenest-akihabara-3.jpg": "211ebaa2be",
  "./img/hotels/thumb/homenest-akihabara-4.jpg": "23b4d3b26e",
  "./img/hotels/thumb/homenest-akihabara-5.jpg": "887adeb0b7",
  "./img/hotels/thumb/homenest-akihabara-6.jpg": "7678b0a836",
  "./img/hotels/thumb/homenest-akihabara.jpg": "34749f1a6c",
  "./img/hotels/thumb/kawaguchiko-2.jpg": "0baa0d76b3",
  "./img/hotels/thumb/kawaguchiko-3.jpg": "0f47d8f622",
  "./img/hotels/thumb/kawaguchiko-4.jpg": "1b3617f644",
  "./img/hotels/thumb/kawaguchiko.jpg": "e31f9a3e89",
  "./img/hotels/thumb/mercure-takayama-2.jpg": "40df8b5eda",
  "./img/hotels/thumb/mercure-takayama-3.jpg": "b1e13dd17d",
  "./img/hotels/thumb/mercure-takayama-4.jpg": "59eada56ab",
  "./img/hotels/thumb/mercure-takayama.jpg": "48bf8fb5b3",
  "./img/hotels/thumb/royal-park-haneda-2.jpg": "27e39feed5",
  "./img/hotels/thumb/royal-park-haneda-3.jpg": "52fd523bb7",
  "./img/hotels/thumb/royal-park-haneda-4.jpg": "788bb9a3b2",
  "./img/hotels/thumb/royal-park-haneda.jpg": "6fd99cf995",
  "./img/icon-180.png": "61ef11573b",
  "./img/icon-192.png": "1cd8513e28",
  "./img/icon-512.png": "d22fb99cd0",
  "./img/logo.svg": "05a44a04b4"
};
// </precache>

async function putFresh(cache, url) {
  const res = await fetch(url, { cache: "reload" });
  if (!res || !res.ok) return;
  const hash = IMG_HASH[url];
  await cache.put(url, hash ? await stamped(res, hash) : res.clone());
}

/** Copie de la réponse marquée de l’empreinte de son contenu (en-tête x-img-hash). */
async function stamped(res, hash) {
  const headers = new Headers(res.headers);
  headers.set("x-img-hash", hash);
  return new Response(await res.clone().blob(), { status: res.status, statusText: res.statusText, headers });
}

async function sha1Short(blob) {
  const buf = await crypto.subtle.digest("SHA-1", await blob.arrayBuffer());
  return Array.from(new Uint8Array(buf), (b) => b.toString(16).padStart(2, "0")).join("").slice(0, 10);
}

/**
 * Image absente ou modifiée depuis sa mise en cache ? (le cache des images est conservé
 * entre les versions : sans ce contrôle, un fichier remplacé sous le même nom resterait figé).
 * Entrée d’avant l’empreinte : on compare le contenu, et on la marque si elle est à jour.
 */
async function isStale(cache, url) {
  const want = IMG_HASH[url];
  const cached = await cache.match(url);
  if (!cached) return true;
  if (!want) return false;
  const have = cached.headers.get("x-img-hash");
  if (have) return have !== want;
  try {
    if ((await sha1Short(await cached.clone().blob())) !== want) return true;
    await cache.put(url, await stamped(cached, want));
  } catch (_) { /* contrôle impossible : on garde l’image */ }
  return false;
}

/** Exécute `task` sur chaque élément, `n` à la fois (une erreur isolée n’arrête rien). */
async function eachParallel(list, n, task) {
  let i = 0;
  const worker = async () => {
    while (i < list.length) {
      const item = list[i++];
      try { await task(item); } catch (_) { /* un échec isolé n’empêche pas l’installation */ }
    }
  };
  await Promise.all(Array.from({ length: n }, worker));
}

self.addEventListener("install", (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    const imgCache = await caches.open(IMG_CACHE);
    // Code, données, vignettes, logo et icônes seulement (≈ 3 Mo d’images) : la mise à jour ne les attend pas
    await eachParallel(ASSETS.filter((u) => !isImage(u)), 6, (url) => putFresh(cache, url));
    await eachParallel(ASSETS.filter((u) => isImage(u) && !isFullPhoto(u)), 6, async (url) => {
      if (await isStale(imgCache, url)) await putFresh(imgCache, url);
    });
    await self.skipWaiting();
  })());
});

/** Photos complètes manquantes, 2 à la fois (laisse la bande passante à ce qui s’affiche). */
async function precacheFullPhotos() {
  const imgCache = await caches.open(IMG_CACHE);
  await eachParallel(ASSETS.filter(isFullPhoto), 2, async (url) => {
    if (await isStale(imgCache, url)) await putFresh(imgCache, url);
  });
}
let photosRun = null;

self.addEventListener("activate", (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((k) => k !== CACHE && k !== TILE_CACHE && k !== IMG_CACHE).map((k) => caches.delete(k)));
    // Ménage : photos retirées du site
    const wanted = new Set(ASSETS.filter(isImage).map((u) => new URL(u, self.location).href));
    const imgCache = await caches.open(IMG_CACHE);
    const stored = await imgCache.keys();
    await Promise.all(stored.filter((r) => !wanted.has(r.url.split("?")[0])).map((r) => imgCache.delete(r)));
    await self.clients.claim();
  })());
});

self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") self.skipWaiting();
  if (event.data && event.data.type === "PRECACHE_IMAGES") {
    if (!photosRun) photosRun = precacheFullPhotos().finally(() => { photosRun = null; });
    event.waitUntil(photosRun);
  }
});

function fetchWithTimeout(req, ms) {
  return Promise.race([
    fetch(req, { cache: "no-store" }),
    new Promise((_, reject) => setTimeout(() => reject(new Error("timeout")), ms))
  ]);
}

async function fallbackPage() {
  return (await caches.match("./index.html")) || (await caches.match("./")) || Response.error();
}

/** Réseau d’abord (avec délai max), copie en cache, sinon version en cache. */
async function networkFirst(req, isPage) {
  try {
    const res = await fetchWithTimeout(req, NETWORK_TIMEOUT_MS);
    if (res && res.ok) {
      const cache = await caches.open(CACHE);
      try { await cache.put(req, res.clone()); } catch (_) { /* quota */ }
    }
    return res;
  } catch (_) {
    const cached = await caches.match(req, { ignoreSearch: true });
    if (cached) return cached;
    return isPage ? fallbackPage() : Response.error();
  }
}

/** Cache d’abord, réseau sinon (et mise en cache — photos dans IMG_CACHE). */
async function cacheFirst(req) {
  const cached = await caches.match(req, { ignoreSearch: true });
  if (cached) return cached;
  try {
    const res = await fetch(req);
    if (res && res.ok) {
      const cache = await caches.open(isImage(new URL(req.url).pathname) ? IMG_CACHE : CACHE);
      cache.put(req, res.clone());
    }
    return res;
  } catch (_) {
    return fallbackPage();
  }
}

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  const path = url.pathname;
  const isPage = req.mode === "navigate" || path.endsWith("/") || path.endsWith("/index.html");
  const isLib = path.includes("/lib/");
  const isApp = !isLib && (
    path.endsWith("sw.js") ||
    path.includes("/src/") ||
    path.includes("/styles/") ||
    path.includes("/data/"));

  event.respondWith(isPage || isApp ? networkFirst(req, isPage) : cacheFirst(req));
});
